### ISSUE TITLE
RPC and Horizon responses should provide clickable XDR links

### ISSUE THREAD

**Issue by janewang** [stellar/laboratory#1009]
### What problem does your feature solve?
Similar to old lab,  responses from the RPC and Horizon that contain XDRs should render as links and be clickable and leads the user to the decoded JSON in the `XDR to JSON` page. 

### What would you like to see?

Old Lab: https://old-lab.stellar.org/#explorer?resource=transactions&endpoint=all&network=public
<img width="1326" alt="Screenshot 2024-09-09 at 10 05 17 PM" src="https://github.com/user-attachments/assets/2f3c2cde-2139-48fe-9124-0e6b3cbd228c">

New Lab: XDR is not clickable
<img width="1306" alt="Screenshot 2024-09-09 at 10 05 51 PM" src="https://github.com/user-attachments/assets/3836ed2c-aa78-4569-ac66-6547bca37236">

**Comment by MonsieurNicolas** [comment]
ran into this with the new `getLedgerEntries` endpoint, both the key and value are not links:
```json
{
  "jsonrpc": "2.0",
  "id": 8675309,
  "result": {
    "entries": [
      {
        "key": "AAAACAAAAAQ=",
        "xdr": "AAAACAAAAAQAACAGAAAAAAAAJxA=",
        "lastModifiedLedgerSeq": 1157
      }
    ],
    "latestLedger": 1591636
  }
}
```
