### ISSUE TITLE
Proposal: Merge params and operations pages when building tx

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/laboratory#1031]
Today the tx params and operations pages are separated in new lab.

I find it disorienting for a couple reasons:

When I'm on the params page, once I've entered all the required fields, there's no transactions or call to action about what to do next. It's not obvious that I need to click the "Add operations" button.

<img width="1579" alt="Screenshot 2024-09-16 at 10 45 15 AM" src="https://github.com/user-attachments/assets/ee83fcc4-a851-4a4f-b28e-0b5024a33cf6">

Once I discover the operations tab I'm on that tab, and the results get displayed below, but I don't see the tx params anymore. When I think like someone new to Stellar, and inexperienced, it's really easy to navigate away, and then back by clicking "Transactions" at the top tab, and I'm back on just the operations view. I edit the operations, and try to submit, but now my tx fails because I don't have a new sequence. It's soo easy to forget the Params page exists at this point.

<img width="1579" alt="Screenshot 2024-09-16 at 10 45 22 AM" src="https://github.com/user-attachments/assets/ef0c3b55-1d8c-42ee-a6d0-cfae91a64864">

**Comment by janewang** [comment]
Close in favor of this ticket with design merging the two tabs: https://github.com/stellar/laboratory/issues/980
