### ISSUE TITLE
Problem: Sign buttons and UI ambiguous

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/laboratory#1034]
The sign UI is ambigious.

1. The `Add Signer` section, has a button `Add Signature`, but it doesn't accept a signature as input, but a signer to produce a signature. The button would be less ambiguous to me if named `Add additional signer`.

2. There are three sign buttons, and it's unclear how they interact. Does `Sign transaction` only sign using signers, or also using the hardware wallet?

   The `Sign transactions` button seems to exclusively work with keys entered at the beginning of the sign box, and the `Sign with wallet` seems to ignore the signers entered. The UI looks like it's signing with all things together, but actually they're all independent.

3. Until clicking `Sign with wallet` it's not obvious what that button is for vs the first button.

<img width="1225" alt="Screenshot 2024-09-16 at 11 17 54 AM" src="https://github.com/user-attachments/assets/696eb71e-928f-48d6-af19-35aca95a09e4">

The separation of functionality was clearer, although still subtle, in old lab:

<img width="1114" alt="Screenshot 2024-09-16 at 11 20 21 AM" src="https://github.com/user-attachments/assets/e84c7b9f-2851-427f-b1a8-16599422c388">

**Comment by janewang** [comment]
Discussed and agreed:
- create more visual separation for Hardware Wallets vs Stellar Wallet Kit
- evaluate the signing flow for ledger wallet

**Comment by quietbits** [comment]
Here are examples of the Old vs. New flow when signing with the Ledger hardware wallet. The Old Lab signs the transaction right away, while the New Lab needs an extra click to do that.

Old Lab

[lab-sign-tx-ledger-old-lab.webm](https://github.com/user-attachments/assets/48c393f4-d24a-4c69-84b2-bae85f8bb459)

New Lab

[lab-sign-tx-ledger-new-lab.webm](https://github.com/user-attachments/assets/3429625d-28a3-4e75-a39b-ec6c017f1c49)

**Comment by janewang** [comment]
Thanks @quietbits 

@quietbits @sdfcharles I think we are missing a few states, like "Waiting for Ledger", then once we show the state "Successfully added a hardware wallet signature", the first button below really should change to "Submit transaction" (because the transaction has been signed). Wdyt?

**Comment by sdfcharles** [comment]
yep agreed, will design those states before our next huddle 🙏

**Comment by sdfcharles** [comment]
updated designs [here](https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=5515-20930&t=TDOOprzTzWvpjquW-1)

ux changes: 
- added separation between signature sections
- updated "Add signature" to "Add additional signer" on signing with secret key
- updated titles to standard format ("Sign with...")
- "Submit in transaction submitter" only shows on the transaction results card
- added in-between loading states for hardware wallet and wallet extension signings
- added success message for hardware wallet and wallet extension signings

cc @janewang @quietbits

**Comment by leighmcculloch** [comment]
The separation in the updated design looks great, and is clearer than previous lab's separation was. 👏🏻 

> * updated "Add signature" to "Add additional signer" on signing with secret key

@sdfcharles Would it also work to automatically display an additional signer text input when a secret key is entered into the previous input? It would alleviate the need for an additional bold button, that would I think make the flow clearer to a user. This might be too minor to worry about at this point.

> * added success message for hardware wallet and wallet extension signings

@sdfcharles I love this. What do you think about adding the same success message to the signer/key box, so that all three types of signing produce the same style of success message? It'd round out the connection between I've hit that button, and it's done.

**Comment by sdfcharles** [comment]
@leighmcculloch 

> Would it also work to automatically display an additional signer text input when a secret key is entered into the previous input? It would alleviate the need for an additional bold button, that would I think make the flow clearer to a user. This might be too minor to worry about at this point.
yep we could do that – would feel more seamless especially if we are also having the user click "Sign with a Secret Key"

> What do you think about adding the same success message to the signer/key box, so that all three types of signing produce the same style of success message? It'd round out the connection between I've hit that button, and it's done.
yep, updated designs to include this success message

**Comment by janewang** [comment]
Design from @sdfcharles  here https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=5516-21433&m=dev
