### ISSUE TITLE
Problem: Submission results are hidden too far below the fold

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/laboratory#1035]
When submitting a transaction the result appears below the fold, so it’s not obvious that anything has happened. It’s easy to sit here waiting for something to happen when the result already loaded below the fold. The result should probably display immediately under the button.

If the decoded xdr didn't display under the button, it would be more obvious when the result became available.

https://github.com/user-attachments/assets/2d8cbddb-8108-4dfd-b316-d0b4f799f723

**Comment by leighmcculloch** [comment]
For a second today when using it, I thought the decoded tx was the result from submission and submission occurred automatically. The placement of that decoded tx on that page is pretty confusing. Maybe it’d be better if there was a link to view the xdr for the tx on the view xdr page? Then the result can display immediately under the button.

**Comment by janewang** [comment]
@sdfcharles Do you think we should add some visual element close to the button indicating the submission occurred?

**Comment by janewang** [comment]
Discussed with @sdfcharles and @quietbits. We will automatically scroll the user to the result of the tx section.
