### ISSUE TITLE
Proposal: Remove the "POST" on saved txs

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/laboratory#1036]
Saved txs have the word "POST" next to them, that looks like a bug, maybe a carry over from a HTTP API.

At a glance it looks like a http endpoint has been saved, when it is a tx.

<img width="1577" alt="Screenshot 2024-09-16 at 11 27 46 AM" src="https://github.com/user-attachments/assets/21b6df0b-f219-4d5b-ab5d-c9e5108dc99a">

**Comment by janewang** [comment]
We should remove the POST
