### ISSUE TITLE
Decode Stellar account data entries in XDR Viewer

### ISSUE THREAD

**Issue by JakeUrban** [stellar/laboratory#1040]
### What problem does your feature solve?

The XDR Viewer's JSON schema for transaction envelopes represents the values included in Manage Data operations as hex-encoded bytes.

Example:
```
AAAAAgAAAACpn2Fr7GAZ4XOcFvEz+xduBFDK1NDLQP875GtWWlJ0XQAAAMgAAAAAAAAAAAAAAAEAAAAAZui9zgAAAABm6MFSAAAAAAAAAAIAAAABAAAAAO9MepiiaK25U1b4YwYgpTuFP/yEsDXt/QPpH49IRCIbAAAACgAAABt0ZXN0YW5jaG9yLnN0ZWxsYXIub3JnIGF1dGgAAAAAAQAAAEBTdkF3YkcwaGtnL2pLdnVjU0Evb2JEVllkK3hDcHEwWkJxQVVtc25oeEtUZjBHOERQYjJTUDBUaUQzYmZGOGFwAAAAAQAAAACpn2Fr7GAZ4XOcFvEz+xduBFDK1NDLQP875GtWWlJ0XQAAAAoAAAAPd2ViX2F1dGhfZG9tYWluAAAAAAEAAAAWdGVzdGFuY2hvci5zdGVsbGFyLm9yZwAAAAAAAAAAAAFaUnRdAAAAQP4YSdIBTKzWOvkGkj0OCJaiMRypFG2C3U4p61eyEa1O+sOsOzqKCpbgM+sgVNwmB1z8u0FWMiUqSZEdT+TslAg=
```

### What would you like to see?

Decode these bytes so users can read these operations' values.

**Comment by janewang** [comment]
@JakeUrban In my opinion this fix should be on the RPC side, not XDR to JSON. As far as the function is concerned, the XDR to JSON page did faithfully convert XDR to JSON. It's just that on the RPC side it's showing hex-encoded bytes instead of human-readable strings

**Comment by JakeUrban** [comment]
I'm not familiar with how the XDR Viewer tab is implemented so I can't speak to where exactly the fix should be made.
