### ISSUE TITLE
Display whether the signature is valid in the XDR View interface

### ISSUE THREAD

**Issue by overcat** [stellar/laboratory#1054]
### What problem does your feature solve?

This can help developers quickly verify if the signature is valid.

### What would you like to see?
In the old version, if the signature is valid, it will be marked with green ✅; if it is invalid, it will be marked with red ❌. However, in the new version, this feature has been removed. Can we add it back?

### What alternatives are there?
N/A

**Comment by janewang** [comment]
Add `Signature Checked` text to show that the signatures are indeed checked 
<img width="1139" alt="360958832-d05e1c87-d776-4dae-953e-4dd3f8c6743b" src="https://github.com/user-attachments/assets/5cbc4325-22b9-470c-bafe-59c239e944e7">
