### ISSUE TITLE
Update 'Soroban RPC' to 'Stellar RPC'

### ISSUE THREAD

**Issue by jeesunikim** [stellar/laboratory#1076]
The Soroban RPC is getting renamed Stellar RPC: https://github.com/stellar/stellar-docs/pull/1009. We may need to make similar updates on Lab.

Some the path from RPC to different parts of the docs may change. Each method page has a link to the docs method page too.

**Comment by janewang** [comment]
I think the PR we are waiting for isn't going in soon: https://github.com/stellar/soroban-rpc/pull/270
