### ISSUE TITLE
Add JSON payload to Saved RPC Endpoints

### ISSUE THREAD

**Issue by sdfcharles** [stellar/laboratory#1077]

**Comment by sdfcharles** [comment]
designs: https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=4271-20298&t=7cRx4cyuOHYHdcTy-1

**Comment by janewang** [comment]
Closed in favor of this ticket https://github.com/stellar/laboratory/issues/1010
