### ISSUE TITLE
Add HelpMark to JSON response

### ISSUE THREAD

**Issue by irisli** [stellar/laboratory#108]
Mockup:
![image](https://cloud.githubusercontent.com/assets/5728307/13585696/1992dedc-e472-11e5-8546-4f448ea78fa1.png)
## Solution

This might be a bit hard to do since the syntax highlighting and link processing is done with the DOM API and not JSX.

We would have to make something similar to `src/utilities/linkHighlightedJson.js`.

**Comment by jedmccaleb** [comment]
I'm not feeling all the "?"  I think it is better to make the words links if we want to do that.

**Comment by irisli** [comment]
If we make them links, we should be careful to differentiate them with links non-docs links.
