### ISSUE TITLE
Remove old results when endpoint fields are reconfigured

### ISSUE THREAD

**Issue by irisli** [stellar/laboratory#109]
It's currently confusing because you can have results for a different endpoint showing for a different set up.

I think we should just completely remove old results instead of showing that it changed (https://github.com/stellar/laboratory/issues/73).

My main thinking is that as a user, when I click a link in the JSON response, I expect things to change. It does scroll the window, but I can still see my old results which confuses me.

**Comment by vcarl** [comment]
Seems to have been implemented! Results clear when endpoint explorer fields are changed.
