### ISSUE TITLE
Connect button for the wallet kit on the top bar should be right aligned

### ISSUE THREAD

**Issue by janewang** [stellar/laboratory#1093]
![Image](https://github.com/user-attachments/assets/303c98ed-c1c0-47f8-9638-40abc4a47c60)

~~Please see design: https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=4271-24144&m=dev~~

**Comment by jeesunikim** [comment]
@sdfcharles i can't update the style because it's a web component from their side. They're working on the design fix based on the figma.

**Comment by jeesunikim** [comment]
by the way the design @janewang linked is super old (look how header's menu and its icon are not on the same line)

**Comment by quietbits** [comment]
@jeesunikim Instead of styling the button to match a specific design, would it be possible to allow passing any button and just add a click event on it? That way, anyone could style it to match their look and feel.
