### ISSUE TITLE
Saved Keypairs: add fund with Friendbot

### ISSUE THREAD

**Issue by quietbits** [stellar/laboratory#1140]
This feature will be helpful after the network resets.

- [ ] Fund with Friendbot button if an account is not active
- [ ] Show XLM balance if an account is active

Design

![Image](https://github.com/user-attachments/assets/0096f047-cac2-4a61-97d8-5f928d4fb466)

**Comment by janewang** [comment]
Message: `Private keys are sensitive and grant full access to your assets. Avoid reusing key pairs from futurenet or testnet on mainnet.`
