### ISSUE TITLE
crash loading seq number in tx builder

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/laboratory#138]
In the tx builder I tried to load a seq number for an account that didn't exist on the test net. Then I switched to the public network where it does exist and it didn't fill in it just wrote out this to the console:

app-f9c363f….js:8 Error: Operation type is required(…)

**Comment by irisli** [comment]
Error messages logged are the same as the ones output in the gray rectangle where the results show. I think that error message is normal and shows up when you have only an account ID and sequence number there.

Are you saying that the error showed up even though the sequence number didn't exist?

**Comment by irisli** [comment]
Also, were you on my PR branch for network name in url query params? There was a bug there that I just fixed (thanks to you :smile:).
