### ISSUE TITLE
Add progress indicator to sequence number and xdr fetchers

### ISSUE THREAD

**Issue by irisli** [stellar/laboratory#139]
As of right now, clicking on the fetch button does not have any visual indicators until the either the end result or error state.

We could add some sort of indicator next to the button/text while the request is fetching. Perhaps a spinning circle.

**Comment by irisli** [comment]
Additionally, clear the current xdr viewer input when loading the latest transaction to try out.

**Comment by janewang** [comment]
Closed as it is already completed in v2
