### ISSUE TITLE
Endpoint explorer results don't clear when changing networks

### ISSUE THREAD

**Issue by irisli** [stellar/laboratory#146]
This is so that users don't change on the network and accidentally believe that the results were updated too.

Suggested by @bartekn in: https://github.com/stellar/laboratory/pull/136

**Comment by quietbits** [comment]
@janewang We're clearing endpoint input data and results when the network changes in v2. It's probably too big an update to do in v1 now.

**Comment by janewang** [comment]
Agreed, I think since we are going to fix this issue in Lab v2, we could close this issue for Lab v1 for now.
