### ISSUE TITLE
Display decoded value of managedata in xdr viewer

### ISSUE THREAD

**Issue by irisli** [stellar/laboratory#151]
On a transactions with managedata, the xdr viewer shows the data value as a base 64 encoded value. This is useful because managedata can contain binary. However, this is confusing because people might expect text and it is not immediately apparent that it is encoded as base64.

```
AAAAAJGppk03hN8HiAHCToSl6hozzGQ39bdwWxbcJ4X9WkOoAAAAZAAAAAAAAAB7AAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAKAAAAAWsAAAAAAAABAAAAGHRlc3Twn5iKINeLM++/ve+/ve+/ve+/vQAAAAAAAAAA
```
### Currently

![image](https://cloud.githubusercontent.com/assets/5728307/14571324/71cbf7ec-02fd-11e6-9ab1-123f4300d8a8.png)
### Mock of what we could do

![image](https://cloud.githubusercontent.com/assets/5728307/14571369/b61f51aa-02fd-11e6-927c-104a54280693.png)

**Comment by irisli** [comment]
This might clutter things up. maybe instead, we can just have badges on the special values to make it clear that the value is base64.

For example, like how the Safari inspector does it
![image](https://cloud.githubusercontent.com/assets/5728307/14575677/42d57c4a-0318-11e6-8f24-13207ef9f477.png)

**Comment by vcarl** [comment]
Resolved!
