### ISSUE TITLE
Fix browser saving functionality to save the laboratory as an offline file

### ISSUE THREAD

**Issue by irisli** [stellar/laboratory#154]
Right now in Chrome, if I save a webpage to my computer and try to use it, it doesn't work.

This use case is useful for those with spotty internet and would like to use the Laboratory for offline signing.

---

Edit; So, it turns out, in order to save the site, i must select "Webpage Complete" in order for it to save the js files.

But, it looks like this:
![image](https://cloud.githubusercontent.com/assets/5728307/14690611/b7aa4d42-0701-11e6-8521-edd731df296c.png)

The bottom one is nonfunctional and links back to stellar.org

**Comment by irisli** [comment]
Maybe we could also build the site as a single offline .html file built by jenkins. Then, it can be downloaded in the releases page of the github project.

**Comment by vcarl** [comment]
If we want to support offline usage, there are better ways to enable that now. Closing this as outdated.
