### ISSUE TITLE
Add new signature types

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/laboratory#169]
hash(x) and hash(tx)  
https://github.com/stellar/stellar-core/issues/846
https://github.com/stellar/stellar-core/issues/965
Need to be able to add these with setoptions and we need to be able to add the preimage of hash(x) as a signature.

**Comment by bartekn** [comment]
Does the user need to enter hex/base64 or strkey encoded hash (new `T` and `X` version prefixes)?

**Comment by bartekn** [comment]
Closed by https://github.com/stellar/laboratory/commit/248935f8f34fa575b7dcc82f75fd884b8d3b7695
