### ISSUE TITLE
inconsistent rendering of amounts in xdr viewer

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/laboratory#180]
Amounts are returned with what seems to be an arbitrary form.

An amount value is returned as either a raw value or both fixed point and raw

Examples:

a trustline will show up with fields (right next to each other):
* `balance: 337698512325` this is the raw value
* `limit: 100000000000 (raw: 1000000000000000000)` both are returned

Lumens are returned the same way, for example in `AccountEntry`, you can see `balance: 105032704` this is raw but in offers and payments it's the fixed point.

In general, I would imagine that any int64 that is supposed to be an amount should be rendered the same way.

**Comment by vcarl** [comment]
Is this still an issue? An XDR to reproduce would be helpful, I'm not quite sure what I'm looking for.

**Comment by MonsieurNicolas** [comment]
yes, you can look at [this example](https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAAQAAAAIAAAADAZQPVAAAAAAAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAHRQ5hwD8MToADEPNAAAABQAAAAEAAAAAPEGtxQtQD1UZU%2BmY3N5z5KtzKggiZYzimTMfGsnpHKQAAAAAAAAAAAEAAAAAAAAAAAAAAQAAABqB%2BNBzAAAAAAAAAAAAAAAAAAAAAAAAAAEBlA9UAAAAAAAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAAdFDmHAPwxOgAMQ84AAAAFAAAAAQAAAAA8Qa3FC1APVRlT6Zjc3nPkq3MqCCJljOKZMx8ayekcpAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAGoH40HMAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAYAAAADAZQPSQAAAAIAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAB3XbIQAAAAFCQVQAAAAAAEZK09vHmzOmEMoVWYtbbZcKv3ZOoo06ckzbhyDIFKfhAAAAAAAAAACOacNhASmKIQBMS0AAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAAHddshAAAAAwGUD1QAAAAAAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAB0UOYcA%2FDE6AAxDzgAAAAUAAAABAAAAADxBrcULUA9VGVPpmNzec%2BSrcyoIImWM4pkzHxrJ6RykAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAagfjQcwAAAAAAAAAAAAAAAAAAAAAAAAABAZQPVAAAAAAAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAHRQ5hwD8MToADEPOAAAABAAAAAEAAAAAPEGtxQtQD1UZU%2BmY3N5z5KtzKggiZYzimTMfGsnpHKQAAAAAAAAAAAEAAAAAAAAAAAAAAQAAABhWkswPAAAAAAAAAAAAAAAAAAAAAAAAAAMBlA9JAAAAAQAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAFCQVQAAAAAAEZK09vHmzOmEMoVWYtbbZcKv3ZOoo06ckzbhyDIFKfhAAAABqz1KIp%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwAAAAEAAAABAAAAAAAAAAAAAAAGrPUoigAAAAAAAAAAAAAAAQGUD1QAAAABAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAUJBVAAAAAAARkrT28ebM6YQyhVZi1ttlwq%2Fdk6ijTpyTNuHIMgUp%2BEAAAAGrPUoin%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAQAAAAEAAAAAAAAAAAAAAAYei2UpAAAAAAAAAAAAAAAGAAAAAwGUD0kAAAACAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAAd12yIAAAABQkFUAAAAAABGStPbx5szphDKFVmLW22XCr92TqKNOnJM24cgyBSn4QAAAAAAAAABHNOGwgAO790AA9CQAAAAAAAAAAAAAAAAAAAAAgAAAAIAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAB3XbIgAAAAMBlA9UAAAAAAAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAAdFDmHAPwxOgAMQ84AAAAEAAAAAQAAAAA8Qa3FC1APVRlT6Zjc3nPkq3MqCCJljOKZMx8ayekcpAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAGFaSzA8AAAAAAAAAAAAAAAAAAAAAAAAAAQGUD1QAAAAAAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAB0UOYcA%2FDE6AAxDzgAAAAMAAAABAAAAADxBrcULUA9VGVPpmNzec%2BSrcyoIImWM4pkzHxrJ6RykAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAT%2B0wjEgAAAAAAAAAAAAAAAAAAAAAAAAADAZQPVAAAAAEAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAABQkFUAAAAAABGStPbx5szphDKFVmLW22XCr92TqKNOnJM24cgyBSn4QAAAAas9SiKf%2F%2F%2F%2F%2F%2F%2F%2F%2F8AAAABAAAAAQAAAAAAAAAAAAAABh6LZSkAAAAAAAAAAAAAAAEBlA9UAAAAAQAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAFCQVQAAAAAAEZK09vHmzOmEMoVWYtbbZcKv3ZOoo06ckzbhyDIFKfhAAAABqz1KIp%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwAAAAEAAAABAAAAAAAAAAAAAAAFAbfeZwAAAAAAAAAAAAAABgAAAAMBlA9JAAAAAgAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAAHddsjAAAAAUJBVAAAAAAARkrT28ebM6YQyhVZi1ttlwq%2Fdk6ijTpyTNuHIMgUp%2BEAAAAAAAAAAas9SiMAJaVhAAmJaAAAAAAAAAAAAAAAAAAAAAIAAAACAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAAd12yMAAAADAZQPVAAAAAAAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAHRQ5hwD8MToADEPOAAAAAwAAAAEAAAAAPEGtxQtQD1UZU%2BmY3N5z5KtzKggiZYzimTMfGsnpHKQAAAAAAAAAAAEAAAAAAAAAAAAAAQAAABP7TCMSAAAAAAAAAAAAAAAAAAAAAAAAAAEBlA9UAAAAAAAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAAdFDmHAPwxOgAMQ84AAAACAAAAAQAAAAA8Qa3FC1APVRlT6Zjc3nPkq3MqCCJljOKZMx8ayekcpAAAAAAAAAAAAQAAAAAAAAAAAAABAAAADWTIUFMAAAAAAAAAAAAAAAAAAAAAAAAAAwGUD1QAAAABAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAUJBVAAAAAAARkrT28ebM6YQyhVZi1ttlwq%2Fdk6ijTpyTNuHIMgUp%2BEAAAAGrPUoin%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAQAAAAEAAAAAAAAAAAAAAAUBt95nAAAAAAAAAAAAAAABAZQPVAAAAAEAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAABQkFUAAAAAABGStPbx5szphDKFVmLW22XCr92TqKNOnJM24cgyBSn4QAAAAas9SiKf%2F%2F%2F%2F%2F%2F%2F%2F%2F8AAAABAAAAAQAAAAAAAAAAAAAAA1Z6lEQAAAAAAAAAAAAAAAYAAAADAZQPSQAAAAIAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAB3XbJAAAAAFCQVQAAAAAAEZK09vHmzOmEMoVWYtbbZcKv3ZOoo06ckzbhyDIFKfhAAAAAAAAAANWepREAmRKywCYloAAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAAHddskAAAAAwGUD1QAAAAAAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAB0UOYcA%2FDE6AAxDzgAAAAIAAAABAAAAADxBrcULUA9VGVPpmNzec%2BSrcyoIImWM4pkzHxrJ6RykAAAAAAAAAAABAAAAAAAAAAAAAAEAAAANZMhQUwAAAAAAAAAAAAAAAAAAAAAAAAABAZQPVAAAAAAAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAHRQ5hwD8MToADEPOAAAAAQAAAAEAAAAAPEGtxQtQD1UZU%2BmY3N5z5KtzKggiZYzimTMfGsnpHKQAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBlA9UAAAAAQAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAFCQVQAAAAAAEZK09vHmzOmEMoVWYtbbZcKv3ZOoo06ckzbhyDIFKfhAAAABqz1KIp%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwAAAAEAAAABAAAAAAAAAAAAAAADVnqURAAAAAAAAAAAAAAAAQGUD1QAAAABAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAUJBVAAAAAAARkrT28ebM6YQyhVZi1ttlwq%2Fdk6ijTpyTNuHIMgUp%2BEAAAAGrPUoin%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAwGUD1QAAAAAAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAB0UOYcA%2FDE6AAxDzgAAAAEAAAABAAAAADxBrcULUA9VGVPpmNzec%2BSrcyoIImWM4pkzHxrJ6RykAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAZQPVAAAAAAAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAHRQ5hwD8MToADEPOAAAAAgAAAAEAAAAAPEGtxQtQD1UZU%2BmY3N5z5KtzKggiZYzimTMfGsnpHKQAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAIrOSb4AAAAAAAAAAAAAAAAAAAAAAAAAAMBlA9UAAAAAQAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAFCQVQAAAAAAEZK09vHmzOmEMoVWYtbbZcKv3ZOoo06ckzbhyDIFKfhAAAABqz1KIp%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQGUD1QAAAABAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAUJBVAAAAAAARkrT28ebM6YQyhVZi1ttlwq%2Fdk6ijTpyTNuHIMgUp%2BEAAAAGrPUoin%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAQAAAAEAAAAAAAAAAAAAAACOacNhAAAAAAAAAAAAAAAAAZQPVAAAAAIAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAB3XbwgAAAAFCQVQAAAAAAEZK09vHmzOmEMoVWYtbbZcKv3ZOoo06ckzbhyDIFKfhAAAAAAAAAACOacNhAAF8uwAAYagAAAAAAAAAAAAAAAAAAAAFAAAAAAGUD1QAAAACAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAAd128MAAAABQkFUAAAAAABGStPbx5szphDKFVmLW22XCr92TqKNOnJM24cgyBSn4QAAAAAAAAABHNOGwgCVUpEAJiWgAAAAAAAAAAAAAAAAAAAAAwGUD1QAAAAAAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAB0UOYcA%2FDE6AAxDzgAAAAIAAAABAAAAADxBrcULUA9VGVPpmNzec%2BSrcyoIImWM4pkzHxrJ6RykAAAAAAAAAAABAAAAAAAAAAAAAAEAAAACKzkm%2BAAAAAAAAAAAAAAAAAAAAAAAAAABAZQPVAAAAAAAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAHRQ5hwD8MToADEPOAAAAAwAAAAEAAAAAPEGtxQtQD1UZU%2BmY3N5z5KtzKggiZYzimTMfGsnpHKQAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAaGJbfJAAAAAAAAAAAAAAAAAAAAAAAAAAMBlA9UAAAAAQAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAFCQVQAAAAAAEZK09vHmzOmEMoVWYtbbZcKv3ZOoo06ckzbhyDIFKfhAAAABqz1KIp%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwAAAAEAAAABAAAAAAAAAAAAAAAAjmnDYQAAAAAAAAAAAAAAAQGUD1QAAAABAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAUJBVAAAAAAARkrT28ebM6YQyhVZi1ttlwq%2Fdk6ijTpyTNuHIMgUp%2BEAAAAGrPUoin%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAQAAAAEAAAAAAAAAAAAAAAGrPUojAAAAAAAAAAAAAAAFAAAAAwGUD1QAAAAAAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAB0UOYcA%2FDE6AAxDzgAAAAMAAAABAAAAADxBrcULUA9VGVPpmNzec%2BSrcyoIImWM4pkzHxrJ6RykAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAGhiW3yQAAAAAAAAAAAAAAAAAAAAAAAAABAZQPVAAAAAAAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAHRQ5hwD8MToADEPOAAAABAAAAAEAAAAAPEGtxQtQD1UZU%2BmY3N5z5KtzKggiZYzimTMfGsnpHKQAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAA0cIU5HAAAAAAAAAAAAAAAAAAAAAAAAAAMBlA9UAAAAAQAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAFCQVQAAAAAAEZK09vHmzOmEMoVWYtbbZcKv3ZOoo06ckzbhyDIFKfhAAAABqz1KIp%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwAAAAEAAAABAAAAAAAAAAAAAAABqz1KIwAAAAAAAAAAAAAAAQGUD1QAAAABAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAUJBVAAAAAAARkrT28ebM6YQyhVZi1ttlwq%2Fdk6ijTpyTNuHIMgUp%2BEAAAAGrPUoin%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAQAAAAEAAAAAAAAAAAAAAANWepRGAAAAAAAAAAAAAAAAAZQPVAAAAAIAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAB3XbxAAAAAFCQVQAAAAAAEZK09vHmzOmEMoVWYtbbZcKv3ZOoo06ckzbhyDIFKfhAAAAAAAAAAGrPUojAEtErQATEtAAAAAAAAAAAAAAAAAAAAAFAAAAAwGUD1QAAAAAAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAB0UOYcA%2FDE6AAxDzgAAAAQAAAABAAAAADxBrcULUA9VGVPpmNzec%2BSrcyoIImWM4pkzHxrJ6RykAAAAAAAAAAABAAAAAAAAAAAAAAEAAAANHCFORwAAAAAAAAAAAAAAAAAAAAAAAAABAZQPVAAAAAAAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAHRQ5hwD8MToADEPOAAAABQAAAAEAAAAAPEGtxQtQD1UZU%2BmY3N5z5KtzKggiZYzimTMfGsnpHKQAAAAAAAAAAAEAAAAAAAAAAAAAAQAAABp%2F1KSCAAAAAAAAAAAAAAAAAAAAAAAAAAMBlA9UAAAAAQAAAAB1m3A%2FFStIp4ybPiuwbAqUFZdVE0htPHeAmDCu9diR%2FAAAAAFCQVQAAAAAAEZK09vHmzOmEMoVWYtbbZcKv3ZOoo06ckzbhyDIFKfhAAAABqz1KIp%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwAAAAEAAAABAAAAAAAAAAAAAAADVnqURgAAAAAAAAAAAAAAAQGUD1QAAAABAAAAAHWbcD8VK0injJs%2BK7BsCpQVl1UTSG08d4CYMK712JH8AAAAAUJBVAAAAAAARkrT28ebM6YQyhVZi1ttlwq%2Fdk6ijTpyTNuHIMgUp%2BEAAAAGrPUoin%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAAAAAQAAAAEAAAAAAAAAAAAAAAas9SiKAAAAAAAAAAAAAAAAAZQPVAAAAAIAAAAAdZtwPxUrSKeMmz4rsGwKlBWXVRNIbTx3gJgwrvXYkfwAAAAAB3XbxQAAAAFCQVQAAAAAAEZK09vHmzOmEMoVWYtbbZcKv3ZOoo06ckzbhyDIFKfhAAAAAAAAAANWepREAmQZVQCYloAAAAAAAAAAAAAAAAA%3D&type=TransactionMeta)

`Account` and `Trustline` have `balance` in raw only, like `balance: 487864711`
Offer `amount` and Trustline `limit` are mixed.

Looks like right now the only gap is on `balance` so rendering it as mixed would probably fix this issue

**Comment by bartekn** [comment]
Would be great to create `type Amount int64` type in stellar-core so finding fields that should be rendered as amounts would be easier.

**Comment by janewang** [comment]
Fixed in new Lab
