### ISSUE TITLE
Display tree view of txblob in signing section

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/laboratory#22]

**Comment by irisli** [comment]
If by tree view of txblob, you mean a summary, then I'm closing this issue:

![image](https://cloud.githubusercontent.com/assets/5728307/12132701/450583d2-b3d3-11e5-984f-eb7083c9684b.png)

If you meant something else (such as full XDR tree view), please do re-open this issue.

**Comment by irisli** [comment]
Though I do agree the summary in the above screenshot could be expanded to have more information.

**Comment by jedmccaleb** [comment]
No I mean the contents of the operations. Like in bartek's xdr viewer

**Comment by irisli** [comment]
Okay, so this is just tree view in general.

**Comment by irisli** [comment]
implemented by: https://github.com/stellar/laboratory/pull/83
