### ISSUE TITLE
/accounts/<accountId>/trades broken

### ISSUE THREAD

**Issue by cecilygardner** [stellar/laboratory#262]
does not show sold_amount, sold_asset_type, bought_amount, bought_asset_type, offer_id

**Comment by cecilygardner** [comment]
➤ Nikhil Saraf commented:

@tomerweller, not sure if you're the best person for this?

**Comment by tomerweller** [comment]
This has been fixed in the horizon side: https://github.com/stellar/go/pull/417
Needs to be re-implemented in laboratory
