### ISSUE TITLE
Effect paging doesn't work

### ISSUE THREAD

**Issue by stysmart** [stellar/laboratory#318]
When you see effect for selected transaction (e.g. https://goo.gl/47WXEq ) and click on _links:next:href, it brings you on the same page (page with empty effect is expected). When accessing the JSON directly, it works fine.

**Comment by Synesso** [comment]
I'm seeing an additional bug at the same URL. Click the `next.href` link and lab tries to open it in testnet, resulting in a 404.

ie. [effects for txn on live network](https://www.stellar.org/laboratory/#explorer?resource=effects&endpoint=for_transaction&values=eyJvcmRlciI6ImFzYyIsImxpbWl0IjoiIiwiY3Vyc29yIjoiIiwidHJhbnNhY3Rpb24iOiIxYmViMWZmZDY5ZWQyNzlmYjQ2Y2RjNjkxZTU2YzMxNjI0MWNjZTNlM2ZiYWFhODYyZGMxZmJmNDQyZDc3NzljIn0%3D&network=public); next points to [404 on test network](https://www.stellar.org/laboratory/#explorer?resource=effects&endpoint=for_transaction&values=eyJvcmRlciI6ImFzYyIsImxpbWl0IjoiMTAiLCJjdXJzb3IiOiI2ODg3MzYxMDIyNzM1NTY0OS0yIiwidHJhbnNhY3Rpb24iOiIxYmViMWZmZDY5ZWQyNzlmYjQ2Y2RjNjkxZTU2YzMxNjI0MWNjZTNlM2ZiYWFhODYyZGMxZmJmNDQyZDc3NzljIn0%3D&network=test).   Removing `-testnet` from the subdomain results in exactly the same page as the first.

**Comment by robertDurst** [comment]
Looking into this.

@Synesso the testnet/pubnet error is fixed as of #316 .
