### ISSUE TITLE
Stellar Laboratory is running in development mode

### ISSUE THREAD

**Issue by dbuarque** [stellar/laboratory#319]
<img width="1217" alt="screen shot 2018-02-11 at 18 56 14" src="https://user-images.githubusercontent.com/559571/36078436-6c22a444-0f5d-11e8-955e-ec9f3ce5bcf1.png">

**Comment by vcarl** [comment]
No it's not!
![Screen Shot 2019-10-01 at 10 13 46 AM](https://user-images.githubusercontent.com/1551487/65970259-2c0d1d00-e434-11e9-8668-63ca3b50473b.png)
