### ISSUE TITLE
Transaction builder allows clear immutable flag

### ISSUE THREAD

**Issue by Synesso** [stellar/laboratory#320]
Which will either be a no-op if immutable flag is false, or a failure if immutable is true.

![screen shot 2018-02-14 at 10 02 20 am](https://user-images.githubusercontent.com/21859/36188911-14290630-119b-11e8-879d-f5c99bd701a2.png)

**Comment by robertDurst** [comment]
Good point -- under no circumstance would/can you ever clear an `Authorization Immutable` flag
