### ISSUE TITLE
Create account operation builder has no `funder` field.

### ISSUE THREAD

**Issue by Synesso** [stellar/laboratory#322]
It doesn't seem possible to specify a funder in lab for create account operation.

I assume that the transaction source, operation source and funder can be three distinct accounts.

<img width="551" alt="screen shot 2018-02-17 at 3 21 57 pm" src="https://user-images.githubusercontent.com/21859/36338284-731c4a32-13f6-11e8-8834-5d5ce388b50d.png">

<img width="1120" alt="screen shot 2018-02-17 at 3 21 44 pm" src="https://user-images.githubusercontent.com/21859/36338286-762b6dac-13f6-11e8-9775-d87cbad0cd76.png">

**Comment by Synesso** [comment]
Then again, [there is no funder field in XDR](https://github.com/stellar/java-stellar-sdk/blob/master/xdr/Stellar-transaction.x#L40-L44). So maybe it's the documentation & horizon API JSON response that are wrong?

**Comment by bartekn** [comment]
Funder is the operation/transaction source account. XDR fields are different than REST API fields.
