### ISSUE TITLE
setOptions - homeDomain is empty string instead of None type after clear it.

### ISSUE THREAD

**Issue by obbaeiei** [stellar/laboratory#330]
**Description**
When typing something in Input block then clear it. After submit that field It's change to empty string instead of None type.

If I would like to change to None after type something. I have to refresh a page or create new operation and remove the old operation.

**Expected behavior**
- After clear input field it should be None type.
- Add some button to set None type. same as Memo.

**Step to reproduce**

1. Create operation type set_options
2. typing something in field Home Domain
3. clear all text in that field

**In the following example for None type and empty string.**

**None type**
[AAAAALpDZVagspfAMfLgaw/esPlpWUf5zy+WM1bLWkvgm7S1AAAAZACOL/AAAAAEAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=](https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAALpDZVagspfAMfLgaw%2FesPlpWUf5zy%2BWM1bLWkvgm7S1AAAAZACOL%2FAAAAAEAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%3D&type=TransactionEnvelope&network=public)

**Empty string** 
[AAAAALpDZVagspfAMfLgaw/esPlpWUf5zy+WM1bLWkvgm7S1AAAAZACOL/AAAAAEAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAA](https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAALpDZVagspfAMfLgaw%2FesPlpWUf5zy%2BWM1bLWkvgm7S1AAAAZACOL%2FAAAAAEAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAA&type=TransactionEnvelope&network=test)

**Comment by robertDurst** [comment]
Thanks for the description @obbaeiei , I was able to reproduce.
