### ISSUE TITLE
some hex fields are displayed as base64

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/laboratory#336]
Found that when viewing certain objects in the XDR Viewer, like `LedgerHeader` (as returned by the `ledgers` endpoint), hash values are base64 encoded (in other places in API etc they are hex encoded):

For example, [this ledger header](https://www.stellar.org/laboratory/#xdr-viewer?input=AAAACVAjytC4kHIYS7km%2BoZ2YZA3UtFQp39Oh7wbLJzn6FYe3Aj4XAYO2rYcNJZpL3pnSrJt1rLazpFCmihcQX42uL8AAAAAWzV5pwAAAAAAAAAAGtdqljXXrf33cr15ZVe9zP23tceUrsnbIt4jjfHpqcJxOzqyjwxZUgTi3%2BEJR4G9u2cCTjd30J%2BezkyqoqwkuAEcmyIOcSZHno%2B3jQAADOkaFo8TAAAA0QAAAAAA%2FgLnAAAAZABMS0AAAAAygDBgwG0KFL5niZMjteoE3%2BTB4rkAg8mGyP%2FpMCfY0viKLceI1w2UW98v%2FDTqlm2uJZVneo%2F4Nre9C0HONLNoc6t8aESrBPWEmTs%2BxbucJWEZ3eoqLyz4zBtGcY4cYvW3kuQw2R%2BMfAuB3ViYKmEXRaY15kNlAJf77PWXPJcRv3MAAAAA&type=LedgerHeader&network=public) returns
```json
previousLedgerHash: UCPK0LiQchhLuSb6hnZhkDdS0VCnf06HvBssnOfoVh4=
```

**Comment by bartekn** [comment]
I'm wondering if we should switch to hex everywhere or create a switch (base64/hex) in XDR viewer section. I think the only places we use base64 are:
* [Account Data Entries](https://horizon-testnet.stellar.org/accounts/GACH7QS2F6DGG7T77B2PJBJU4YGKZ5RGMSUNJAV4SBSZGSULTGYS565I),
* Memo Hash, serialized XDRs and signatures in [transaction](https://horizon-testnet.stellar.org/transactions/509340b64d4b86649cefedeccf83a61e866fe1768b0ea265308fcf66d44f874a).

Everything else could be hex.

**Comment by MonsieurNicolas** [comment]
Now that I think of it, the problem is that we don't want to give the wrong data for developers:
* humans (like me) when debugging want something consistent with core/horizon's database
* for machines, it's probably better to not mix hex/base64

Maybe the easiest is to output by default whatever the API returns (that machines consume), and simply make elements clickable, which would toggle between hex/base64/raw string.
