### ISSUE TITLE
JS error on streaming

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/laboratory#349]
https://www.stellar.org/laboratory/#explorer?resource=effects&endpoint=for_account&values=eyJhY2NvdW50X2lkIjoiR0FIM01RNklKWjdRQTRMVDY1N0FHVVRWUjdIM0IzUVFLQlo0WTRGS0lBU1U3VVNBTzVRVE1IMlgiLCJzdHJlYW1pbmciOnRydWUsImN1cnNvciI6Im5vdyJ9&network=public and look at the console.

**Comment by robertDurst** [comment]
Ah I see.


[Here](https://github.com/stellar/js-stellar-sdk/blob/master/src/call_builder.js#L21) we call:
```javascript
this.url.segment()
```

which causes the following error:
```shell
Uncaught TypeError: Cannot read property 'segment' of undefined
```

since we are trying to call a function on an undefined property. Fixed if we just specify the url as part of the initial `CallBuilder` instantiation.
