### ISSUE TITLE
Clearing master weight or thresholds in set options sets it to 0 instead of undefined

### ISSUE THREAD

**Issue by pselden** [stellar/laboratory#351]
**Repro steps:**

1. Go to https://www.stellar.org/laboratory/#txbuilder?params=eyJhdHRyaWJ1dGVzIjp7InNvdXJjZUFjY291bnQiOiJHQ1ZIRUtTUkFTSkJENk8yWjUzMkxXSDROMlpMQ0JWRExMVExLU1lDU01CTE9ZVE5NRUVHVUFSRCIsInNlcXVlbmNlIjoiNzIxMDQ4MDg2MTM0MTI4NjcifSwib3BlcmF0aW9ucyI6W3siaWQiOjAsImF0dHJpYnV0ZXMiOnsiaW5mbGF0aW9uRGVzdCI6IkdDQ0Q2QUpPWVpDVUFRTFgzMlpKRjJNS0ZGQVVKNTNQVkNGUUkzUkhXS0wzVjQ3UVlFMkJOQVVUIn0sIm5hbWUiOiJzZXRPcHRpb25zIn1dfQ%3D%3D&network=test
2. Click on View in XDR Viewer and observe that master weight is undefined (will not be set with this transaction)
3. Go back to the transaction builder and enter "1" for the Master Weight in the Set Options operation
4. Delete the "1" you just entered
5. Go back to the View in XDR Viewer

**Expected:**

Should have undefined in the master weight, since it is not explicitly set in the UI

**Actual:**

Sets the master weight to 0

Note: this also happens for any of the threshold fields

**Why this is bad:**

If you accidentally type in a value into master weight and then delete it, you may accidentally set your master weight to 0, locking yourself out of your account.

I actually had a support ticket on StellarGuard where someone was trying to manually configure the StellarGuard signer and ended up locking their own private key out (luckily thresholds was also set to 0 due to this bug and I was able to reset the master weight via the StellarGuard signer).

**Comment by robertDurst** [comment]
Error is that

```javascript
if (_.isString(value) && value.match(/^[0-9]*$/g)) {
    return Number(value);
  }
```

passes for an empty string, which in the world of javascript returns 0 since Number("") = 0
