### ISSUE TITLE
Cannot sign

### ISSUE THREAD

**Issue by michelem09** [stellar/laboratory#355]
Hello,
I'm trying to sign a tx on https://www.stellar.org/laboratory/ but I get console errors and cannot go ahead.

<img width="2100" alt="screen shot 2018-08-28 at 10 11 06" src="https://user-images.githubusercontent.com/439555/44709859-f1a3b480-aaaa-11e8-914f-96e684fcd2a4.png">

**Comment by michelem09** [comment]
It seems this problem is not present before this commit https://github.com/stellar/laboratory/commit/b7ab1cf7522811a503535d2e3bb5b800a68248b3

So I think that introduced a bug.

**Comment by bartekn** [comment]
Thanks for reporting this. Version before b7ab1cf deployed to https://www.stellar.org/laboratory. We will fix it soon.
