### ISSUE TITLE
Bug in signature verification

### ISSUE THREAD

**Issue by MisterTicot** [stellar/laboratory#360]
I'm playing with binary data in text memo, and found a transaction whose signatures are valid but laboratory XDR viewer pretends the opposite:

[See in XDR viewer](https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAAMkQlWAlY2qv0pGOjMhHoRYYEHJSUPsbk4gDJLh48EzUAAAAZAAKl98AAAAMAAAAAAAAAAEAAAADABCDAAAAAAEAAAAAAAAACgAAAARTZW5kAAAAAQAAAAMQUYcAAAAAAAAAAAJ48EzUAAAAQE2zHs80i1YVXWSXBMSYxO9yisKbTCYXGU2Vj8gDVC%2FDzyH%2FnVMUTCLpq%2BrePe9bZgFQ9biW%2BTKIrAug92DrEgmxj%2BffAAAAQFBxRqCVBTsdfEUP7mG9OA3scxv3Ay1HDmqKMb16RUOq2Nr1BTGrAhnAl2YbIbWy2zzbROXHS0NCw5IvaZnXBAw%3D&type=TransactionEnvelope&network=test)

The transaction is actually published on the network:

[See in explorer](https://www.stellar.org/laboratory/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjA2NjBhMjc3YTk3NGRmZDhiODUxNWRkZTJlZWNmZTkzNzc2NzgwYTk1YTI2Y2E4YmQzYzg2YTVkMzg2MjMwYmEifQ%3D%3D&network=test)

**Comment by bartekn** [comment]
Thanks, this has been fixed in [`stellar-sdk@0.11.0`](https://github.com/stellar/js-stellar-sdk/releases/tag/v0.11.0) but Laboratory's `package.json` was not updated. Will be deployed later today.

Fix in https://github.com/stellar/laboratory/commit/22c49944075b0bec9d6c6f64f035934d25e7506b.
