### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Vishwas1** [stellar/laboratory#361]
I am getting this error when running `gulp develop`

ERROR ;  `regeneratorRuntime is not defined`

**Comment by vikramIde** [comment]
I tried updating the babel version and added 

```
 module: {
    loaders: [
      {test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader',query: {
         presets: ['react', "@babel/preset-es2016"],
        plugins: ['@babel/plugin-transform-runtime']
      }},
      {test: /\.json$/, loader: 'json'},
      {test: /\.scss/, loader: ExtractTextPlugin.extract('css?sourceMap!sass?sourceMap')},
      {test: /\.html$/, loader: 'file?name=[name].html'},
      {test: /\.(jpe?g|png|gif|svg)$/, loader: 'file?name=images/[hash].[ext]'}
    ]
  },
````
at line 29

but the issue is not yet reso,lved

**Comment by bartekn** [comment]
Did you use `yarn` to install dependencies? What is your Node version?

**Comment by Vishwas1** [comment]
This is not an issue. I tried with `yarn install` and it worked fine. Not sure why it didnt work with `npm i` though.

**Comment by sgehrman** [comment]
I can't get it running with npm or yarn.  Will fix and submit a PR.

**Comment by markusschaden** [comment]
I used yarn 1.16.0 and node 8.16.0 to build the sources.
```
yarn install
yarn run build
```
Which worked
