### ISSUE TITLE
Account creation fails for a custom network

### ISSUE THREAD

**Issue by OwenJacob** [stellar/laboratory#366]
I am using Stellar Laboratory to test a private Stellar network however the account creation step does not seem to be able to create and fund accounts on the network.

Steps to replicate:
1. Select custom network and add the Horizon URL and Network Passphrase
2. Account creation step 1: Generate custom key pair
3. Account creation step 2: Fund the account using the Friendbot
4. Laboratory indicates account is successfully funded but the Horizon logs on our network indicate no request was ever received.
5. Use the Laboratory endpoint explorer to check the account ID. Horizon logs show the request is received from Laboratory but of course Horizon returns 404 because the account was never actually created.

Expected outcome:
Account creation step 2 sends request to custom network Horizon URL and account is created within the custom network allowing it to be used with the endpoint explorer and the other tools of Stellar Laboratory.

**Comment by bartekn** [comment]
You need your own `friendbot` service for custom networks. What you could do is just create account from a master account (secret of the master account = `sha256(network_passphrase`, it's also displayed when you run `stellar-core --newdb`) .
