### ISSUE TITLE
Fill builder form using existing transaction

### ISSUE THREAD

**Issue by bartekn** [stellar/laboratory#375]

**Comment by vcarl** [comment]
I got this feature working on a prototype I worked on earlier this year, I started from [`extrapolateFromXdr.js`](https://github.com/stellar/laboratory/blob/master/src/utilities/extrapolateFromXdr.js) and made some adjustments to fit it to a new purpose. I don't recall specifically what changes I had to make, but the [resulting code is here](https://github.com/stellar/lab-next/blob/master/src/helpers/parseTransactionEnvelope.js), which then gets used [here](https://github.com/stellar/lab-next/blob/master/src/helpers/transactionBuilder.js#L28) to build form state.

We might be able to use some of that logic to build our state, and then make some adjustments to [`reducers/transactionBuilder.js`](https://github.com/stellar/laboratory/blob/master/src/reducers/transactionBuilder.js) to make use of the data.
