### ISSUE TITLE
Protocol 11 updates

### ISSUE THREAD

**Issue by bartekn** [stellar/laboratory#377]
https://github.com/stellar/stellar-core/releases/tag/v11.0.0

**Comment by tomquisel** [comment]
Todo:

- [ ] rename `MANAGE_OFFER` to `MANAGE_SELL_OFFER`
- [ ] add support for `MANAGE_BUY_OFFER`

@bartekn anything else?

**Comment by bartekn** [comment]
@tomquisel updated you comment.
