### ISSUE TITLE
Friendbot should be disabled when non test networks are selected

### ISSUE THREAD

**Issue by tomerweller** [stellar/laboratory#380]
as friendbot is only active on the test network

**Comment by vcarl** [comment]
The Friendbot button in question is [here](https://github.com/stellar/laboratory/blob/master/src/components/AccountCreator.js#L81-L84). We know which network we're on from the `network` field of [the redux state](https://github.com/stellar/laboratory/blob/master/src/components/AccountCreator.js#L17) this component receives. Can compare that with [constants from the `constants/network.js`](https://github.com/stellar/laboratory/blob/master/src/constants/network.js) file to check what the active network is.

**Comment by vcarl** [comment]
This is not quite done, the link to friendbot still appears.

![](https://user-images.githubusercontent.com/1551487/66775500-24b52d00-ee92-11e9-81f7-9363667bc3ce.png)
