### ISSUE TITLE
You shouldn't have to specify a base fee in the lab

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/laboratory#382]
Currently in tx builder you are required to specify a fee when you create a transaction (rather than using a default, such as the min fee). You shouldn't have to enter this unless you want to.

**Comment by theaeolianmachine** [comment]
Hey @morleyzhi, is this because we upgraded the JS library for the lab? I didn't see a specific PR for this.

**Comment by vcarl** [comment]
I've looked into this briefly, there are some refactors that need to be done to support this. Transactions are built in [`TxBuilderResult`'s render method](https://github.com/stellar/laboratory/blob/master/src/components/TxBuilderResult.js#L34) using the [`Libify.buildTransaction` helper](https://github.com/stellar/laboratory/blob/master/src/utilities/Libify.js#L313). The helper needs to be changed to return a promise, and the actual generation needs to be treated as async (with loading state, final results, and any errors being kept in state).
