### ISSUE TITLE
txBuilder − Manage Buy Offer − Offer ID should be optional

### ISSUE THREAD

**Issue by MisterTicot** [stellar/laboratory#386]
It's all in the title. Currently the interface forces user to enter an offerId parameter, which doesn't match the network behavior.

**Comment by jeesunikim** [comment]
Hmm it doesn't say it's optional on the doc https://www.stellar.org/developers/guides/concepts/list-of-operations.html#manage-buy-offer

**Comment by jeesunikim** [comment]
We will update it so that if a user didn't specify a value in `Offer ID` input, it will be set to 0.

**Comment by MisterTicot** [comment]
Yes it does... Just look at the JS doc, that's the API you use :

https://stellar.github.io/js-stellar-sdk/Operation.html#.manageBuyOffer

**Comment by jeesunikim** [comment]
You're right. 

We will update so that:
1) `offerId`'s default value is 0 (this isn't clear on laboratory at the moment)
2) Add an `optional` attribute
