### ISSUE TITLE
TxBuilder − Fees is not optional anymore

### ISSUE THREAD

**Issue by MisterTicot** [stellar/laboratory#387]
With protocol 11 update, fees parameter is not optional anymore. The interface correctly raise an error if user doesn't provide it. However, the "(optional)" mention under `Base Fee` label should be removed. Alternatively, the interface could fill that parameter automatically using NetworkBaseFee which would lead to a better experience.

**Comment by vcarl** [comment]
This is resolved as part of #389 by removing the "(optional)" mention. I looked into allowing the fee to be automatically filled with the recommended fee from /fee_stats, but it looks like the transaction building logic assumes it can execute synchronously. To me it looks like a substantial refactor to enable promises, but I can add `StellarSDK.BASE_FEE` as a default value.

**Comment by vcarl** [comment]
Fixed in #389.
