### ISSUE TITLE
Operations look disabled when there's none selected

### ISSUE THREAD

**Issue by msfeldstein** [stellar/laboratory#394]
In the transaction builder, all the operations available are greyed out even though they're available.  It works, it just looks broken.
![Screenshot 2019-08-22 at 11 37 49 AM](https://user-images.githubusercontent.com/161135/63540725-787a4a00-c4d1-11e9-865a-b80d106d2ee1.png)

**Comment by vcarl** [comment]
Are you still seeing this @msfeldstein? It looks correct for me in both Chrome and Safari on Mac.
![Screen Shot 2019-09-30 at 3 16 09 PM](https://user-images.githubusercontent.com/1551487/65908874-58259100-e395-11e9-855c-fee1a025ae1c.png)

**Comment by msfeldstein** [comment]
im seeing it on firefox for mac.  the `.so-dropdown__select--placeholder` color is what makes it look that way
