### ISSUE TITLE
Feature Request: Convert the unix timestamp you enter in the time bounds to human readable

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/laboratory#428]
Convert the unix timestamp you enter for the time bounds of a tx to something human readable and display it somewhere outside the edit box.

**Comment by janewang** [comment]
We will need a design to parse UNIX to convert to human readable timestamp

**Comment by sdfcharles** [comment]
designs here: https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=5008-68883&t=ViYwtCoC7XOhoHpP-1

![Image](https://github.com/user-attachments/assets/addb14c5-82c6-48b3-806b-c8648328f856)
