### ISSUE TITLE
Pre-signed transaction doesn't submit, but stays "loading" forever

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/laboratory#430]
### What version are you using?

Current deployed version at www.stellar.org/laboratory as of 2019-12-19.

### What did you do?

Tried to submit this pre-signed transaction at Endpoint Explorer->Transactions->Post Transaction:
```
AAAAAGjEO6b/++00uc1YpgKQXsQsuNM06P8+taS0Fn6atJ53AAAAZAGawdEAAAADAAAAAAAAAAAAAAABAAAAAAAAAAoAAAAKbWVtYmVyc2hpcAAAAAAAAAAAAAAAAAABmrSedwAAAEBCuuGxRH/dZY47zJ0vTnqqcnEwiJCJdvDjFbs1McxqgawejVsgCDaUZxt/fxd+G6fcoHIsDlayUSi09VPYL8kK
```
URL: https://www.stellar.org/laboratory/#explorer?resource=transactions&endpoint=create&values=eyJ0eCI6IkFBQUFBR2pFTzZiLysrMDB1YzFZcGdLUVhzUXN1Tk0wNlA4K3RhUzBGbjZhdEo1M0FBQUFaQUdhd2RFQUFBQURBQUFBQUFBQUFBQUFBQUFCQUFBQUFBQUFBQW9BQUFBS2JXVnRZbVZ5YzJocGNBQUFBQUFBQUFBQUFBQUFBQUFCbXJTZWR3QUFBRUJDdXVHeFJIL2RaWTQ3ekowdlRucXFjbkV3aUpDSmR2RGpGYnMxTWN4cWdhd2VqVnNnQ0RhVVp4dC9meGQrRzZmY29ISXNEbGF5VVNpMDlWUFlMOGtLIn0%3D&network=public

### What did you expect to see?

A failure message (this TX has already been submitted).

### What did you see instead?

"Loading..." appears at the bottom of the screen, and never resolves to success or failure.

![image](https://user-images.githubusercontent.com/1606404/71195413-bc444c80-2242-11ea-8e02-0dc27d0924c8.png)

**Comment by bartekn** [comment]
Horizon returns `400 Bad Request`:
```json
{
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/guides/concepts/list-of-operations.html",
  "extras": {
    "envelope_xdr": "AAAAAGjEO6b/++00uc1YpgKQXsQsuNM06P8+taS0Fn6atJ53AAAAZAGawdEAAAADAAAAAAAAAAAAAAABAAAAAAAAAAoAAAAKbWVtYmVyc2hpcAAAAAAAAAAAAAAAAAABmrSedwAAAEBCuuGxRH/dZY47zJ0vTnqqcnEwiJCJdvDjFbs1McxqgawejVsgCDaUZxt/fxd+G6fcoHIsDlayUSi09VPYL8kK",
    "result_codes": {
      "transaction": "tx_bad_seq"
    },
    "result_xdr": "AAAAAAAAAAD////7AAAAAA=="
  }
}
```
but GUI of Laboratory is not updated.

**Comment by vcarl** [comment]
That's no good! Taking a look.

**Comment by vcarl** [comment]
Looks like axios changed how they emit errors and I didn't catch it when I tested #420.

**Comment by vcarl** [comment]
Signed testnet transaction I was testing with:
```
AAAAABNaHhXu+oxbXbhnaYqXadcG8Lp5kPc6/BjUvVHtvQ9qAAAAZAAC94YAAAABAAAAAQAAAAAAAAAAAAAAAF8s+p8AAAAAAAAAAQAAAAAAAAABAAAAABNaHhXu+oxbXbhnaYqXadcG8Lp5kPc6/BjUvVHtvQ9qAAAAAAAAAAA7msoAAAAAAAAAAAHtvQ9qAAAAQNkRuaXK7TJSjddKqMWUH+Cwneta3rc4OMCMIa8ry9L8wiJ9UCmR8K+hyaSMSPnSgNs2YKqWthW6kXL7aeehVw4=
```
Can also [submit directly](http://localhost:3000/laboratory/#explorer?resource=transactions&endpoint=create&values=eyJ0eCI6IkFBQUFBQk5hSGhYdStveGJYYmhuYVlxWGFkY0c4THA1a1BjNi9CalV2Vkh0dlE5cUFBQUFaQUFDOTRZQUFBQUJBQUFBQVFBQUFBQUFBQUFBQUFBQUFGOHMrcDhBQUFBQUFBQUFBUUFBQUFBQUFBQUJBQUFBQUJOYUhoWHUrb3hiWGJobmFZcVhhZGNHOExwNWtQYzYvQmpVdlZIdHZROXFBQUFBQUFBQUFBQTdtc29BQUFBQUFBQUFBQUh0dlE5cUFBQUFRTmtSdWFYSzdUSlNqZGRLcU1XVUgrQ3duZXRhM3JjNE9NQ01JYThyeTlMOHdpSjlVQ21SOEsraHlhU01TUG5TZ05zMllLcVd0aFc2a1hMN2FlZWhWdzQ9In0%3D&network=test)

**Comment by ire-and-curses** [comment]
Confirmed fix works in preview. I see the Horizon error returned now. :+1:
