### ISSUE TITLE
Endpoint Explorer for Offers > Single Offer > SEARCH ERROR

### ISSUE THREAD

**Issue by JahanzebNawaz** [stellar/laboratory#440]
### What version are you using?
 (laboratory.stellar.org) Test Network for gettings details regarding OrderID. 

### What did you do?

i just put my OrderID but that doesn't show us the result,
the reason why it does not show us the result is the concatenation of  2 URLs 
   
      https://horizon-testnet.stellar.orghttps://horizon-testnet.stellar.org/offers/{offer_id}
     

### What did you expect to see?
     Result of OrderID and details. if the links issues resolve then it will be able to show us the required results.

### What did you see instead?
     Nothing it keeps processing.

### Attaching screenshot
![Screenshot from 2020-04-11 01-48-24](https://user-images.githubusercontent.com/34652154/79022877-5fc1c000-7b98-11ea-829b-ed6e9c7cd08e.png)

**Comment by vcarl** [comment]
Good catch @JahanzebNawaz! Thanks
