### ISSUE TITLE
Dead link in XDR viewer

### ISSUE THREAD

**Issue by jacekn** [stellar/laboratory#442]
### What version are you using?

I'm using https://laboratory.stellar.org

### What did you do?

[XDR viewer](https://laboratory.stellar.org/#xdr-viewer?type=TransactionEnvelope&network=test) links to [External Data Representation (XDR)](https://www.stellar.org/developers/horizon/guides/xdr.html) which returns 404

### What did you expect to see?

HTTP 200

### What did you see instead?

HTTP 404

**Comment by vcarl** [comment]
I did a quick scan for other dead links with a similar pattern, looks like this is the only one
