### ISSUE TITLE
Building and signing transactions is done synchronously

### ISSUE THREAD

**Issue by vcarl** [stellar/laboratory#458]
`TxBuilderResult.js` [builds transactions](https://github.com/stellar/laboratory/blob/master/src/components/TxBuilderResult.js#L30) and `TransactionSigner.js` [signs transactions](https://github.com/stellar/laboratory/blob/master/src/components/TransactionSigner.js#L51) as part of their `render` methods, which means we can't do anything asynchronous as part of this. We would like to be able to fetch some information to make building transactions easier (#387 for example) but can't because of this constraint.

**Comment by janewang** [comment]
This is irrelevant. As a general direction, we are decomposing build tx and signing tx in most tools
