### ISSUE TITLE
/order_book?

### ISSUE THREAD

**Issue by jobforp** [stellar/laboratory#46]
uses alphanumeric on order book example

Documentation uses credit_alphanum4

https://www.stellar.org/developers/horizon/reference/orderbook-details.html

**Comment by jedmccaleb** [comment]
Ah right needs to be fixed to support both asset types

**Comment by irisli** [comment]
This issue has been fixed by https://github.com/stellar/laboratory/commit/827703502d16d63a085382c396a17a65a56cbedd

It will go live once the general-improvements branch is merged and deployed. Thanks!
