### ISSUE TITLE
Feature Request: Add signature to transaction

### ISSUE THREAD

**Issue by tomerweller** [stellar/laboratory#476]
### What problem does your feature solve?
Sometimes a user wants to add a signature to a transaction envelope without having access to the signing key. One example is when combining multiple signatures (multisig orchestration) from various signers.

### What would you like to see?
In the "Sign Transaction" tab add a "Add Signature" section that takes in two fields: a b64 encoded signature and a public key.
I also suggest making the following copy edits to disambiguate the various signing methods: 

"Add Signer" -> "Sign with Secret Key"
"Ledger Wallet" -> "Sign with Ledger Wallet" 

### What alternatives are there?
- Writing code that does the above
- Orchestrate key signing serially - but that's less efficient
- An alternative lab feature is to have an explicit "merge signatures" tab that takes in two tx envelope xdrs and outputs a new tx envelope xdr with a combined list of decorated signatures (worth checking that the txs are binary equal). This is easier for the multisig case but not as generic as just adding a signature.

**Comment by janewang** [comment]
Design from @sdfcharles https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=5516-21433&m=dev
