### ISSUE TITLE
Update XDR Viewer to support Protocol 14 changes

### ISSUE THREAD

**Issue by bartekn** [stellar/laboratory#482]
### What problem does your feature solve?

Stellar-Core v14 has been released which means that XDR structures for Protocol 14 won't change. It will help with debugging and developing Protocol 14 features if [XDR Viewer](https://laboratory.stellar.org/#xdr-viewer) was updated to support new structures.

### What would you like to see?

XDR Viewer supports new structures like `ClaimableBalance`.

### What alternatives are there?

Manual decoding.

**Comment by quietbits** [comment]
Upgrading `stellar-sdk` to v6.0.0 added support for new Protocol 14 structures.
