### ISSUE TITLE
Make "Sign in with BIP path" button secondary

### ISSUE THREAD

**Issue by gbaranski** [stellar/laboratory#494]
Thats about this button

<img width="1134" alt="Screen_Shot_2020-10-31_at_19 25 52" src="https://user-images.githubusercontent.com/34353640/97787419-576fb780-1bb2-11eb-94d9-95d87728657d.png">

And thats the bottom, in my opinion only one should be primary
<img width="1134" alt="Screen_Shot_2020-10-31_at_19 26 14" src="https://user-images.githubusercontent.com/34353640/97787422-63f41000-1bb2-11eb-96f9-8648a77951da.png">

**Comment by gbaranski** [comment]
I'll make a pull request in a moment, just need to finish quest.

**Comment by janewang** [comment]
Irrelevant with Lab v2 design, closing
