### ISSUE TITLE
Link of help mark of field Home Domain in operation "Set Options"  points to "additional signing keys"

### ISSUE THREAD

**Issue by Kanaye** [stellar/laboratory#507]
The link of the Help Mark of the field "Home Domain" in the operation "Set Options" points to the documentation for additional signing keys.

https://github.com/stellar/laboratory/blob/f6a72c5521b755244a2c77a1f2b3af3db7cfa866/src/components/OperationPanes/SetOptions.js#L105

I'm not sure where it hsould link to, but additional signing keys is definitly wrong.
Maybe: https://developers.stellar.org/docs/issuing-assets/publishing-asset-info/#how-to-publish-your-stellartoml ?

**Comment by janewang** [comment]
Closing since v2 Lab launched
