### ISSUE TITLE
Display `claimable_balance_id` to the user after submitting a CreateClaimableBalanceOp

### ISSUE THREAD

**Issue by marcelosalloum** [stellar/laboratory#508]
### What
Display `claimable_balance_id` to the user after submitting a transaction with `CreateClaimableBalanceOp`.

### Why
When you create a claimable balance you need the `claimable_balance_id` in order to claim it. The full spec can be found in [CAP-23](https://github.com/stellar/stellar-protocol/blob/028f5b4859f7894caadd2c6006c11b5168155cc1/core/cap-0023.md)

Nowadays we need to access the effects created by the operation in order to gather the `claimable_balance_id`, as in https://horizon-testnet.stellar.org/operations/5875708534460417/effects.

### What alternatives are there?
Since we can gather the `claimable_balance_id` before submitting the transaction, we could display it somewhere in the box where the claimable balance operation is collecting the details:
![Screen Shot 2021-01-19 at 12 12 32](https://user-images.githubusercontent.com/1952597/105069805-33a96880-5a61-11eb-8683-6f0945a96379.png)

We should also add it to the XDR viewer if that is possible when viewing a transaction.

More info can be found in [this slack thread](https://stellarfoundation.slack.com/archives/CTGJ17JCA/p1611068273007300).

**Comment by leighmcculloch** [comment]
The claimable balance is known by the client before the transaction is submitted – it is not generated by the server – and so it there's little reason to rely on a response to get it. I think we should display it on the page somewhere in the box where the claimable balance operation is collecting the details.

**Comment by leighmcculloch** [comment]
We should also add it to the XDR viewer if that is possible when viewing a transaction.

**Comment by marcelosalloum** [comment]
Cool, just updated the issue description with that info and suggestion.

**Comment by janewang** [comment]
Use the note / detail component for the id
