### ISSUE TITLE
bogus warning "Error checking signatures..." when reviewing transactions

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/laboratory#517]
I was playing around on a testnet account, and after signing a transaction for an account freshly generated by friend bot, I saw after submitting the transaction that it said "Error checking signatures" in red.

I suspect that the signature checking code is not using the proper network to verify.

**Comment by quietbits** [comment]
I confirmed that the signatures are validated correctly when using a freshly created account with friendbot to create and sign a transaction in this PR for Lab v2: https://github.com/stellar/laboratory/pull/1000
