### ISSUE TITLE
SetOptions red warning message is scary and ambiguous

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/laboratory#518]
The laboratory displays the below message when the `SetOptions` panel is open, which is ambiguous and scary. It displays the message even if the user is not changing the thresholds so it implies that using any SetOptions operation could lock the account which is unnecessarily scary.

I think we should only display the scary message if someone enters a value in those fields, and instead of saying "This" which is ambiguous, change it to "Changing thresholds can...", or better yet, describe the situation specifically such as "Setting thresholds below account signer weights can...".

Thoughts?

<img width="966" alt="Screen Shot 2021-03-15 at 2 43 32 PM" src="https://user-images.githubusercontent.com/351529/111225263-d3d0c900-859c-11eb-8e68-399c8c1c8700.png">

**Comment by ire-and-curses** [comment]
I think what we have is just the shortest path to a warning implementation.

I support only displaying the message on change of a field.

I'm not in favour of being more specific because of the many bad edge cases (https://github.com/stellar/laboratory/issues/463#issuecomment-651413557) that depend on exactly how you screw up your options which wouldn't be explained.

**Comment by janewang** [comment]
@sdfcharles We still have red messages in Lab v2, but the engineers are split between red vs non-red. These weights could brick the account. Could you take a look at the design and let us know anything needs to change.

**Comment by sdfcharles** [comment]
Lab v2 error messages look fine in red. Let's just update the text to be a statement, rather than a question. Suggested copy:

`This can result in a permanently locked account. Please make sure you understand this function before proceeding.`
