### ISSUE TITLE
Feature Request: Display transaction hash in all places that the base64 is shown

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/laboratory#521]
### What problem does your feature solve?
There is one place in the laboratory ui where we display the transaction hash alongside the transaction base64 blob. It's very convenient. This is on the Sign Transaction tab:

<img width="1114" alt="Screen Shot 2021-04-28 at 1 11 17 PM" src="https://user-images.githubusercontent.com/351529/116466362-3adfcf80-a823-11eb-9e1d-25c1b953ce97.png">

There are a number of other places where we display transaction base 64 without the hash, and it would be convenient if we included them there too. Those places are:
- Submit Transaction tab
- View XDR tab

<img width="1114" alt="Screen Shot 2021-04-28 at 1 12 09 PM" src="https://user-images.githubusercontent.com/351529/116466448-58149e00-a823-11eb-948e-9718b008a487.png">

This would be especially helpful in cases where transaction submission fails and it would be helpful to be able to lookup the transaction on Horizon. To do that the user needs the transaction hash, but it isn't displayed.

<img width="1114" alt="Screen Shot 2021-04-28 at 1 13 12 PM" src="https://user-images.githubusercontent.com/351529/116466603-8f834a80-a823-11eb-9c8c-522a19885d3a.png">

### What would you like to see?

I'd like to see the transaction hash displayed underneath any box that shows transaction XDR/base64.

### What alternatives are there?

It is possible to copy base64 and import it into the Sign Transaction tab and view the hash there, but this is inconvenient.

**Comment by leighmcculloch** [comment]
@accordeiro @quietbits On frequent occasions I continue to find that this feature would be useful. If it's not a big feature, I think it'd be worth doing this when we have some downtime.

**Comment by janewang** [comment]
This will be addressed in Lab v2. The transaction hash is displayed in a response with a link to [View on stellar.expert]
<img width="472" alt="Screenshot 2024-03-12 at 10 05 19 AM" src="https://github.com/stellar/laboratory/assets/734336/324bc612-c428-49d2-bffa-22e32f00bfb0">
