### ISSUE TITLE
Timebounds handling is broken

### ISSUE THREAD

**Issue by matejcik** [stellar/laboratory#541]
In transaction builder, timebounds handling is behaving badly.

1. It is not possible to not set timebounds.

When I leave timebounds fields empty, the generated XDR contains the timebounds field set to two zeros.

(Aside: is this even legal? The network accepts it but it seems such transaction is semantically equivalent to one that omits the timebounds field. In Trezor we conflate timebounds 0/0 with unset, omit the field, and the produced signature is invalid for the provided XDR. We could fix that, but I'm not particularly happy with allowing this sort of weirdness. I am inclined to instead reject transaction that has timebounds set but zero.)

2. It is not possible to set only lower timebound.

When I fill out lower timebound but leave upper timebound unset, the resulting XDR has timebounds 0/0 again.

This makes it difficult to investigate https://github.com/trezor/trezor-firmware/issues/1699

**Comment by tomerweller** [comment]
> It is not possible to not set timebounds.

That's an interesting point. Maybe Laboratory should allow this. However, the [js sdk](https://github.com/stellar/js-stellar-sdk)  doesn't allow bypassing the time-bounds check. We'll file an issue and discuss over the js-sdk.  

> It is not possible to set only lower timebound.

This is how the stellar protocol works. Timebounds are always set together. as evident in the [XDR definitions](https://github.com/stellar/stellar-core/blob/master/src/xdr/Stellar-transaction.x#L529). 0/0 timebonuds are legal according to the protocol and effectively mean that the transactions is always valid from a timebonuds perspective. Trezor should support this.

**Comment by leighmcculloch** [comment]
> It is not possible to not set timebounds.

To build the full variety of XDR that can technically be generated, including not set the time bounds, I recommend using the [stc] tool. It allows you to use simple text files to construct any valid XDR.

[stc]: https://github.com/xdrpp/stc

**Comment by tomerweller** [comment]
@matejcik, you will rarely see a transaction being submitted without timebounds as most sdks enforce this. It is also recommended by the [dev docs](https://developers.stellar.org/docs/glossary/transactions/#time-bounds):
> We highly advise for all transactions to use time bounds, and many SDKs enforce their usage. If a transaction doesn’t make it into the transaction set, it is kept around in memory in order to be added to the next transaction set on a best-effort basis. Because of this behavior, we highly advise that all transactions are created with time bounds in order to invalidate transactions after a certain amount of time, especially if you plan to resubmit your transaction at a later time.

**Comment by matejcik** [comment]
Dne pá 23. 7. 2021 0:53 uživatel tomerweller ***@***.***>
napsal:

> It is not possible to set only lower timebound.
>
> This is how the stellar protocol works.
>

no, the issue here is that Laboratory doesn't allow me to set timebounds
999/0. When the upper timebound is set to 0, the resulting XDR has
timebounds 0/0

>

**Comment by matejcik** [comment]
> you will rarely see a transaction being submitted without timebounds

This is good to know.
However, my problem is that zero timebounds are still legal, as it is to omit the timebounds fields completely.
(To be extra clear: when I say _omit timebounds_, I mean that the _optional_ field `timeBounds` in the transaction is unset. When I say _timebounds 0/0_, i mean that the field `timeBounds` is set to two zeroes. Two transactions that are semantically identical can differ in whether the `timeBounds` field is set or unset.)

Note that Laboratory did support omitting timebounds in the past! Our test vectors are generated through Laboratory and we omit timebounds in most of them.

Trezor currently doesn't support setting timebounds to 0/0. If you submit a transaction that has timebounds 0/0, Trezor will sign a transaction where timebounds are omitted.

We could explicitly allow timebounds 0/0 as separate from "no timebounds", but it would look identical for the user, which is undesirable.

We could also reject transactions that do not set timebounds, and only allow explicitly setting to 0/0. It seems that you think this is preferable, correct?

**Comment by matejcik** [comment]
> However, the [js sdk](https://github.com/stellar/js-stellar-sdk) doesn't allow bypassing the time-bounds check.

despite that, Laboratory sets timebounds to 0/0 by default, allows me to submit and sign such transaction, and it is accepted by the network.

**Comment by tomerweller** [comment]
> no, the issue here is that Laboratory doesn't allow me to set timebounds 999/0. When the upper timebound is set to 0, the resulting XDR has timebounds 0/0

You're right! That appears to be a bug.

> Note that Laboratory did support omitting timebounds in the past! Our test vectors are generated through Laboratory and we omit timebounds in most of them.

Yeah, I believe your test vectors predate the sdk timebounds enforcement. [stc](https://github.com/xdrpp/stc) is a more low level transaction builder and can give you more freedom in building test vectors.  

> despite that, Laboratory sets timebounds to 0/0 by default, allows me to submit and sign such transaction, and it is accepted by the network.

Right again, I should have been clearer. The sdk checks that timebounds are set, but doesn't care about the value. So 0/0 passes the sdk test and is a valid transaction so you can sign it and it will be accepted by the network. 

> We could also reject transactions that do not set timebounds, and only allow explicitly setting to 0/0. It seems that you think this is preferable, correct?

I don't think trezor should be opinionated about this. Both are valid and in both cases trezor should sign the exact transaction it's sent.

**Comment by quietbits** [comment]
Setting min timebounds only should be fixed: https://github.com/stellar/laboratory/pull/542

**Comment by matejcik** [comment]
> > We could also reject transactions that do not set timebounds, and only allow explicitly setting to 0/0. It seems that you think this is preferable, correct?
> 
> I don't think trezor should be opinionated about this. Both are valid and in both cases trezor should sign the exact transaction it's sent.

Keep in mind that Trezor doesn't accept Stellar's interchange formats directly. In particular, here I'm considering setting `timebounds_start` and `timebounds_end` to `required` in the protobuf schema, so it would technically be impossible to send a timebounds-less transaction to Trezor. You call it "opinionated", I'm calling it "removing a feature (that was buggy to begin with)" ;)

Properly fixing the feature does not introduce any significant complexity so that's not an issue, regardless of how this discussion goes. However, I'm wondering if there's any point in keeping it, when your own SDK rejects such transactions.
Any results from the SDK discussion you mentioned in https://github.com/stellar/laboratory/issues/541#issuecomment-885286366 ?

**Comment by shanzzam** [comment]
@matejcik Please join the discussion in the SDK github repo https://github.com/stellar/js-stellar-base/issues/438.
I'd like to close this issue as we've addressed the actual bug here; the ability to only set the min timebounds. The rest of the discussion can happen at the SDK base level. Please let us know if this unblocks trezor/trezor-firmware#1699

**Comment by matejcik** [comment]
> I'd like to close this issue as we've addressed the actual bug here

agreed, closing
