### ISSUE TITLE
Feature Request: Add Albedo as transaction signer

### ISSUE THREAD

**Issue by ralphilius** [stellar/laboratory#545]
### What problem does your feature solve?
When user want to sign a transaction on mobile, neither of the third party options are available. 

![image](https://user-images.githubusercontent.com/4253551/127428251-4a765504-862e-42a4-bf22-fc22f61c7de8.png)

### What would you like to see?
A **Sign with Albedo** button on Sign Transaction screen

**Comment by hanseartic** [comment]
this could be closed as completed
