### ISSUE TITLE
Lab Refactor: Tier 2: XdrViewer

### ISSUE THREAD

**Issue by shanzzam** [stellar/laboratory#564]
- [ ] Create e2e test for XdrViewer
 - [ ] Convert XdrViewer page to TS and implement [style guide](https://github.com/stellar/product-conventions/blob/master/STYLEGUIDE.md); identify potential future design changes
 - [ ] Convert XdrViewer subcomponents
 - [ ] Replace Redux connect with hooks in XdrViewer; use hooks for state
 - [ ] Convert TransactionSigner subcomponents to TS and implement style guide; identify potential future design changes

**Comment by quietbits** [comment]
Closing in favor of the v2 rebuild
