### ISSUE TITLE
Lab Refactor: Tier 2: OperationsBuilder

### ISSUE THREAD

**Issue by shanzzam** [stellar/laboratory#566]
- [ ] Create e2e test for OperationsBuilder
- [ ] Convert OperationsBuilder to TS and implement style guide; identify potential future design changes
- [ ] Reorg getOperation
- [ ] Replace Redux connect with hooks in OperationsBuilder; use hooks for state

**Comment by quietbits** [comment]
Closing in favor of the v2 rebuild
