### ISSUE TITLE
Feature Request: added MuxedAccount support for FeeBump transactions.

### ISSUE THREAD

**Issue by overcat** [stellar/laboratory#608]
### What problem does your feature solve?

In the XDR definition, feeSource is a [MuxedAccount](https://github.com/stellar/stellar-core/blob/c00bcbee11/src/xdr/Stellar-transaction.x#L656), but I got an error when I tried to use MuxedAccount as feeSource.

<img width="1127" alt="fee-bump" src="https://user-images.githubusercontent.com/2368403/132266740-4f84069a-93b4-4eee-a650-2beeea0bb19d.png">

### What would you like to see?
Support using M-Address as feeSource

### What alternatives are there?
None

**Comment by quietbits** [comment]
Thanks for reporting this, @overcat ! 🙌 We'll look into this.

**Comment by quietbits** [comment]
@overcat this should be fixed now. Please take a look and let us know if there are any issues. 🙏
