### ISSUE TITLE
Timebounds reset after memo is changed

### ISSUE THREAD

**Issue by matejcik** [stellar/laboratory#612]
### What version are you using?

Today's deployed version on laboratory.stellar.org

### What did you do?

1. Fill out the following transaction parameters in Builder:
	Source account: `GAXSFOOGF4ELO5HT5PTN23T5XE6D5QWL3YBHSVQ2HWOFEJNYYMRJENBV`
	Sequence: `1000`
	Base fee: `100`
	Memo: `Hash`
	Hash text: `0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef`
	Time bounds: `1` to `1000`

	Operation: **Payment**
	Destination: `GBOVKZBEM2YYLOCDCUXJ4IMRKHN4LCJAE7WEAEA2KF562XFAGDBOB64V`
	Asset: `native`
	Amount: `50.0111`
2. click View in XDR viewer
3. observe that timebounds are set as 1/1000
4. click Back, or click Build Transaction in the menu
5. observe that timebounds are displayed as 1/1000
6. change Memo type to `None`
7. click View in XDR viewer

### What did you expect to see?

Timebounds in XDR should be set to 1/1000, as shown on the previous page

### What did you see instead?

Timebounds in XDR are set to 0/0

I need to _delete_ existing timebounds and re-type or re-paste to update the values in XDR

**Comment by quietbits** [comment]
Thanks for reporting this bug, @matejcik ! [The fix](https://github.com/stellar/laboratory/pull/613) will be merged soon.
