### ISSUE TITLE
UI hangs on response when funding with friendbot

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/laboratory#614]
### What version are you using?

hosted version `https://laboratory.stellar.org/#account-creator?network=test`

### What did you do?

attempt to fund account with friendbot

### What did you expect to see?

funding successful when it succeeded

### What did you see instead?

the `Loading...` text remained even though the account was successfully funded. I kept waiting until I decided to actually check manually against horizon whether it had succeeded

see screenshots of UI and web console for stack trace 

![Screen Shot 2021-09-23 at 11 03 43 AM](https://user-images.githubusercontent.com/1028334/134533303-fbe3f63d-a887-4c65-aa77-9f6df304a187.png)

![Screen Shot 2021-09-23 at 11 04 12 AM](https://user-images.githubusercontent.com/1028334/134533307-0de34c1b-1d82-4191-a59b-1e77c8cfc84e.png)

**Comment by nikhilsaraf** [comment]
Note: I tried for a different account right after and it worked, so may not be very easy to reproduce. May only happen on first attempt or something like that

**Comment by shanzzam** [comment]
I tested this multiple times on different browsers on Mac (FF, Brave, Chrome, Safari) and couldn't replicate this. I used the built-in dev tools on Brave and Chrome to simulate slow network speeds as well. Is it possible there was a network interruption on your user end?

**Comment by nikhilsaraf** [comment]
that is possible. it has happened before on my current connection. Seems safe to close this in that case. sorry for the misreport.
