### ISSUE TITLE
Build Transaction UI shows error message when setting Threshold or Weight to 255

### ISSUE THREAD

**Issue by Row-Bear** [stellar/laboratory#615]
### What version are you using?

-Version at https://laboratory.stellar.org/ on 2021/11/03

### What did you do?

Build a 'Set options operation' to change the master weight.
UI indicates values of 0-255 are allowed (in line with https://developers.stellar.org/docs/glossary/multisig/#thresholds )

### What did you expect to see?
-UI allows input of 255

### What did you see instead?
Upon entering 255 as value, UI shows a red error message
![image](https://user-images.githubusercontent.com/60758353/140196214-3f4db262-4873-4009-9dc9-ad3b136dc36f.png)

Same occurs for setting thresholds
The operation can be built and submitted, this seems limited to the UI

**Comment by quietbits** [comment]
Thanks, @Row-Bear, for reporting this issue! We'll fix it shortly.
