### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by Row-Bear** [stellar/laboratory#616]
### What problem does your feature solve?

Explore Endpoints -> Liquidity Pools -> All Liquidity Pools can not filter for pools that hold native reserves
Only Alphanumeric4 and Alphanumeric12 assets are selectable.
![image](https://user-images.githubusercontent.com/60758353/140197807-69dac3c1-f26b-464f-a5bc-c4133968980b.png)

### What would you like to see?
A toggle/selector to choose Native asset

### What alternatives are there?
Manual manipulation of the URL for the GET request allows for searching liquidity pools that have native reserves
https://horizon.stellar.org/liquidity_pools?reserves=native

**Comment by quietbits** [comment]
Thanks for the suggestion, @Row-Bear! 🙌 It will be added shortly.
