### ISSUE TITLE
Lab Refactor: Tier 3: Fix StellarSDK fromXDR error

### ISSUE THREAD

**Issue by piyalbasu** [stellar/laboratory#623]
On page load, `StellarSdk.TransactionBuilder.fromXDR` in `actions/xdrViewer`'s `fetchSigners` always throw an error. This has no effect on page load, but should be fixed.

<img width="1469" alt="Screen Shot 2021-12-02 at 3 49 23 PM" src="https://user-images.githubusercontent.com/6789586/144501055-c01b733e-4c21-403a-8bde-b1a2dbf2d995.png">

**Comment by quietbits** [comment]
Closing in favor of the v2 rebuild
