### ISSUE TITLE
Lab Refactor: Tier 3: Fix extrapolateFromXdr

### ISSUE THREAD

**Issue by piyalbasu** [stellar/laboratory#634]
extrapolateFromXdr doesn't work in node seemingly because node handles Buffers differently than the browser. This makes it impossible to test properly in @testing-library/react.

This is also true of actions/xdrViewer/fetchSigners. In Node, Buffers don't have an `equals` method, which throws an error.

Refactor theseto work across both engines.

**Comment by quietbits** [comment]
Closing in favor of the v2 rebuild
