### ISSUE TITLE
Updates for Protocol 19

### ISSUE THREAD

**Issue by quietbits** [stellar/laboratory#649]
Related to https://github.com/stellar/laboratory/pull/647.

- [ ] Show `payload` as `hex`

![image](https://user-images.githubusercontent.com/7346473/166297951-f2585ec2-f2e4-487d-b9ff-221d40178004.png)

- [ ] Look into updating how we render signatures (currently it renders incorrectly for Protocol 19)

![image](https://user-images.githubusercontent.com/7346473/166298364-37fb14f4-18fa-445c-8e82-4e34b2a65458.png)

**Comment by janewang** [comment]
Protocol 19 released a long time ago. Closing
