### ISSUE TITLE
Linking with query params does not work regularly

### ISSUE THREAD

**Issue by pselden** [stellar/laboratory#650]
### What did you expect to see?

When following a link with an embedded XDR to the stellar laboratory, it gets cleared the first time it loads and no XDR is filled.

Example: https://laboratory.stellar.org/#txsigner?xdr=AAAAAgAAAADuiUE35l5wFE242f0OpDIsGECverWm%2FQqzpEQ4YJXgrwAAAMgBKQlCAAAABAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAACqcipRBJIR%2BdrPd6XY%2FG6ysQajWua1SwKTArdibWEIagAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAAAAAAEAAAAAGOv%2BNpxvB3ONssNGBFyaLo7FvBE0g8vEgPRDhISwyEEAAAAAAAAAAAAAAAA%3D&network=public will just take you to https://laboratory.stellar.org/#txsigner?network=public.

However, if you repaste the same link while already on the laboratory, it correctly fills.

### What did you see instead?

I expect to be taken to the proper laboratory page with the XDR filled.

**Comment by MonsieurNicolas** [comment]
I also ran into this, it's not super reliable it seems: on Firefox (121.0.1 64-bit Windows), it never works for me (so I have to follow the workaround from above), but on Edge (also on Windows) it seems to work just fine.

It seems the problem occurs with other tabs, like [XDR viewer](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAADznxmN41pu9cu1i0CqOFhuvqtH8xtxcsUtvFZjx8ZQCACdE8MAAA8gAAABKwAAAAIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAPOfGY3jWm71y7WLQKo4WG6%2Bq0fzG3FyxS28VmPHxlAIAAAAGAAAAAAAAAABmIGNmGOKFnc%2F%2FBNL08JnUeGr%2BaLI5Tb1It57Op%2F7%2FMUAAAAJc2V0X3ByaWNlAAAAAAAAAwAAABIAAAAAAAAAAPOfGY3jWm71y7WLQKo4WG6%2Bq0fzG3FyxS28VmPHxlAIAAAAEAAAAAEAAAAQAAAACgAAAAAAAAAAO4BzDppTZUMAAAAKAAAAAAAAAAADgXG8%2BgSK4gAAAAoAAAAAAAAAAAAAWvcxd1DtAAAACgAAAAAAAAAAAAAz89l9bnQAAAAKAAAAAAAAAAAAIMmocLTxXQAAAAoAAAAAAAAAAAAAWvmclqokAAAACgAAAAAAAAAAAAAx6iAKZ4IAAAAKAAAAAAAAAAAADMUB6naq5gAAAAoAAAAAAAAAAAACsnsZNPFdAAAACgAAAAAAAAAAAABOrYaMWSYAAAAKAAAAAAAAAAAABQal%2B%2FhoFgAAAAoAAAAAAAAAAAAAWvYRESjNAAAACgAAAAAAAAAAAAOJV5yXA7UAAAAKAAAAAAAAAAAAAArZxF3CoAAAAAoAAAAAAAAAAAACWCl855YmAAAACgAAAAAAAAAAAABi9XgwuA0AAAAFAAABjQAwk4AAAAABAAAAAAAAAAAAAAABmIGNmGOKFnc%2F%2FBNL08JnUeGr%2BaLI5Tb1It57Op%2F7%2FMUAAAAJc2V0X3ByaWNlAAAAAAAAAwAAABIAAAAAAAAAAPOfGY3jWm71y7WLQKo4WG6%2Bq0fzG3FyxS28VmPHxlAIAAAAEAAAAAEAAAAQAAAACgAAAAAAAAAAO4BzDppTZUMAAAAKAAAAAAAAAAADgXG8%2BgSK4gAAAAoAAAAAAAAAAAAAWvcxd1DtAAAACgAAAAAAAAAAAAAz89l9bnQAAAAKAAAAAAAAAAAAIMmocLTxXQAAAAoAAAAAAAAAAAAAWvmclqokAAAACgAAAAAAAAAAAAAx6iAKZ4IAAAAKAAAAAAAAAAAADMUB6naq5gAAAAoAAAAAAAAAAAACsnsZNPFdAAAACgAAAAAAAAAAAABOrYaMWSYAAAAKAAAAAAAAAAAABQal%2B%2FhoFgAAAAoAAAAAAAAAAAAAWvYRESjNAAAACgAAAAAAAAAAAAOJV5yXA7UAAAAKAAAAAAAAAAAAAArZxF3CoAAAAAoAAAAAAAAAAAACWCl855YmAAAACgAAAAAAAAAAAABi9XgwuA0AAAAFAAABjQAwk4AAAAAAAAAAAQAAAAAAAAABAAAAB4Q5%2F%2F8rXMtOluJ3XGniJ%2FLD9a5a9BZdUmulDer6wVMQAAAAEQAAAAYAAAABmIGNmGOKFnc%2F%2FBNL08JnUeGr%2BaLI5Tb1It57Op%2F7%2FMUAAAAJAAABjQAwk4AAAAAAAAAAAAAAAAAAAAAGAAAAAZiBjZhjihZ3P%2FwTS9PCZ1Hhq%2FmiyOU29SLeezqf%2B%2FzFAAAACQAAAY0AMJOAAAAAAAAAAAEAAAAAAAAABgAAAAGYgY2YY4oWdz%2F8E0vTwmdR4av5osjlNvUi3ns6n%2Fv8xQAAAAkAAAGNADCTgAAAAAAAAAACAAAAAAAAAAYAAAABmIGNmGOKFnc%2F%2FBNL08JnUeGr%2BaLI5Tb1It57Op%2F7%2FMUAAAAJAAABjQAwk4AAAAAAAAAAAwAAAAAAAAAGAAAAAZiBjZhjihZ3P%2FwTS9PCZ1Hhq%2FmiyOU29SLeezqf%2B%2FzFAAAACQAAAY0AMJOAAAAAAAAAAAQAAAAAAAAABgAAAAGYgY2YY4oWdz%2F8E0vTwmdR4av5osjlNvUi3ns6n%2Fv8xQAAAAkAAAGNADCTgAAAAAAAAAAFAAAAAAAAAAYAAAABmIGNmGOKFnc%2F%2FBNL08JnUeGr%2BaLI5Tb1It57Op%2F7%2FMUAAAAJAAABjQAwk4AAAAAAAAAABgAAAAAAAAAGAAAAAZiBjZhjihZ3P%2FwTS9PCZ1Hhq%2FmiyOU29SLeezqf%2B%2FzFAAAACQAAAY0AMJOAAAAAAAAAAAcAAAAAAAAABgAAAAGYgY2YY4oWdz%2F8E0vTwmdR4av5osjlNvUi3ns6n%2Fv8xQAAAAkAAAGNADCTgAAAAAAAAAAIAAAAAAAAAAYAAAABmIGNmGOKFnc%2F%2FBNL08JnUeGr%2BaLI5Tb1It57Op%2F7%2FMUAAAAJAAABjQAwk4AAAAAAAAAACQAAAAAAAAAGAAAAAZiBjZhjihZ3P%2FwTS9PCZ1Hhq%2FmiyOU29SLeezqf%2B%2FzFAAAACQAAAY0AMJOAAAAAAAAAAAoAAAAAAAAABgAAAAGYgY2YY4oWdz%2F8E0vTwmdR4av5osjlNvUi3ns6n%2Fv8xQAAAAkAAAGNADCTgAAAAAAAAAALAAAAAAAAAAYAAAABmIGNmGOKFnc%2F%2FBNL08JnUeGr%2BaLI5Tb1It57Op%2F7%2FMUAAAAJAAABjQAwk4AAAAAAAAAADAAAAAAAAAAGAAAAAZiBjZhjihZ3P%2FwTS9PCZ1Hhq%2FmiyOU29SLeezqf%2B%2FzFAAAACQAAAY0AMJOAAAAAAAAAAA0AAAAAAAAABgAAAAGYgY2YY4oWdz%2F8E0vTwmdR4av5osjlNvUi3ns6n%2Fv8xQAAAAkAAAGNADCTgAAAAAAAAAAOAAAAAAAAAAYAAAABmIGNmGOKFnc%2F%2FBNL08JnUeGr%2BaLI5Tb1It57Op%2F7%2FMUAAAAJAAABjQAwk4AAAAAAAAAADwAAAAAAAAAGAAAAAZiBjZhjihZ3P%2FwTS9PCZ1Hhq%2FmiyOU29SLeezqf%2B%2FzFAAAAFAAAAAEAyaZRAABkpAAACzwAAAAAAAR9QwAAAAHMpdlgAAAAQGud7op18aeMsmH%2FKKpUFDPvZr8EK6NZuMAnIED3FmTG9Ya%2F2pAQ130kNoao5yzMqCPqTl96hEmxjpbz3HHM5Q4%3D&type=TransactionEnvelope&network=test)

**Comment by janewang** [comment]
State issue related to Lab v1. Closing
