### ISSUE TITLE
Lab to prevent users from proceeding if an error occurs

### ISSUE THREAD

**Issue by jeesunikim** [stellar/laboratory#654]
### What version are you using?

https://laboratory.stellar.org

### What did you do?

Sending myself `0.0000001 USDC`.

<img width="970" alt="test" src="https://user-images.githubusercontent.com/3912060/175376397-815b9dea-bca7-4a04-bbd4-9ecf4e8ec068.png">

### What did you expect to see?

Since I got an error, I won't be able to move on to the next step.

### What did you see instead?

It threw an error, but it still let me proceed with completing the transaction.

**Comment by janewang** [comment]
Issue no longer occuring on Lab v2
