### ISSUE TITLE
query params simply don't work, other routing issues.

### ISSUE THREAD

**Issue by silence48** [stellar/laboratory#699]
yeah as the title sais query params don't work for example #xdr-viewer="xdrenvelope"
It can be fixed.
there is other issues with links that get generated to horizon urls when you click them it loads up like it wants to redirect to view a different explore endpoints view but that doesn't work. it just loads nothing, it should either redirect to the view it references (the same thing happens in the links in the json responses) or it should open a new tab and let you view the endpoint.
![image](https://github.com/stellar/laboratory/assets/35656692/41963ac0-4b98-4c6f-8ecb-b70aeb5067c2)

### What did you do?
visit a url like i showed, 
or go to explorer and click on a url for horizon.
### What did you expect to see?
the xdr from the query param, or the horizon endpoints raw json in a new tab, or the new view in explore endpoints.

### What did you see instead?
either no redirect or state change, or no xdr information.

**Comment by janewang** [comment]
Routing issues related to Lab v1. Fixed in Lab v2
