### ISSUE TITLE
Add navigation back to stellar.org/developers

### ISSUE THREAD

**Issue by litnerdy** [stellar/laboratory#70]
Some folks may get to the laboratory via an external link. These developers may not know where to find further documentation. Even people who navigate from the "tools" section of the dev portal may have trouble finding their way back:

![screen shot 2016-02-05 at 2 54 00 pm](https://cloud.githubusercontent.com/assets/8799534/12861459/571b4478-cc18-11e5-931a-5a4d2a8750eb.png)

 I'd suggest applying the top menu from the dev portal, if possible:

![screen shot 2016-02-05 at 2 50 54 pm](https://cloud.githubusercontent.com/assets/8799534/12861402/ef3543ea-cc17-11e5-9283-87471a52ba43.png)

**Comment by irisli** [comment]
This would be something nice to have, though it is a complicated issue to solve that will require a bit of redesign. A simple way would be to add on a footer

**Comment by litnerdy** [comment]
Footer would be a great fix for now. Would that still be a ton of work though?

**Comment by irisli** [comment]
It's more just about figuring out where we are going to put it
