### ISSUE TITLE
Transaction Builder Page UI Crash

### ISSUE THREAD

**Issue by SyedMuqeetAqib** [stellar/laboratory#710]
### What version are you using?
0.0.1 in package-lock.json

### What did you do?
on https://laboratory.stellar.org/#txbuilder page is crashing when user tries to enter transaction details, more specifically for me the page is crashing when user tries to build a transaction with "change trust" operation and after adding asset type and asset code when user enters issuer address, the page crashes.

### What did you expect to see?
The page should not crash and it should let user continue tx building process while showing relevant tx status of being successful or error

### What did you see instead?
white screen (crash)

**Comment by janewang** [comment]
Closing as we launched Lab https://lab.stellar.org/
