### ISSUE TITLE
Cannot sign with Trezor

### ISSUE THREAD

**Issue by vinamogit** [stellar/laboratory#721]
### What did you do?

Signing a transaction in the lab with a Trezor

### What did you expect to see?

A signed transaction

### What did you see instead?

A spinning forever trezor connect

It looks like the lab need to be updated the same way the account viewer was.
https://github.com/stellar/account-viewer-v2/pull/399

**Comment by quietbits** [comment]
PR: https://github.com/stellar/laboratory/pull/728
