### ISSUE TITLE
documentation: CONTRIBUTING.md

### ISSUE THREAD

**Issue by Row-Bear** [stellar/laboratory#724]
### What version are you using?

October 2023

### What did you do?

I clicked the link to the Contributing Guidelines in CONTRIBUTING.md

### What did you expect to see?

I expected the current version of the Stellar Contributing Guidelines: https://github.com/stellar/.github/blob/master/CONTRIBUTING.md

### What did you see instead?

I arrived at the deprecated guidelines at https://github.com/stellar-deprecated/docs/blob/master/CONTRIBUTING.md

Further, CONTRIBUTING.md also links to a google form for the Contributor License Agreement, which the current Stellar CONTRIBUTING.md does not mention. Is that still required?

**Comment by leighmcculloch** [comment]
Thanks for reporting. Fixing in:
- https://github.com/stellar/laboratory/pull/958

**Comment by janewang** [comment]
Fixed above. Closing
