### ISSUE TITLE
Testnet friendbot is actually futurenet friendbot

### ISSUE THREAD

**Issue by vinamogit** [stellar/laboratory#732]
Hi,

As you can see in this screenshot, the testnet friendbot talks about Soroban, when you try to fund an account, the account is funded on futurenet.

![Testnet friendbot](https://github.com/stellar/laboratory/assets/49946720/9c4d37af-74c4-46d3-ab76-736d1de652c6)

**Comment by quietbits** [comment]
Thanks for reporting this bug, @vinamogit ! Here's a PR to fix it: https://github.com/stellar/laboratory/pull/733.
