### ISSUE TITLE
Change secret key fields type to "password"

### ISSUE THREAD

**Issue by bartekn** [stellar/laboratory#75]
We should hide the contents:

![zrzut ekranu 2016-02-11 o 17 04 09](https://cloud.githubusercontent.com/assets/464938/12981564/8288b406-d0e1-11e5-9c34-4038e049fcd6.png)

**Comment by jedmccaleb** [comment]
I disagree. People shouldn't be using this if they need to maintain privacy. We should favor clarity

**Comment by bartekn** [comment]
On the other hand, making this input hidden will also teach people that their secret key it something *like* password and should be protected.

**Comment by irisli** [comment]
I can see arguments for both sides, but i'm not strongly favoring one or the other. I think it would be nice to show the corresponding public key though.

**Comment by cyberomin** [comment]
@jedmccaleb and @irisli, this concern came up while I was recording this video - https://www.youtube.com/watch?v=iNMD70BKU8w. There is a part of the Steller Open Institute that requires people to make sample transaction, albeit for learning purposes. I favour hiding the secret key, but I'm also fine with the teams decision.

**Comment by irisli** [comment]
Perhaps if we make the input a password input and show the public key right below, it would be clear enough but would also hide things. I'm still not entirely convinced that we need to hide it though.

**Comment by litnerdy** [comment]
I'd vote for having the secret key be obscured by default, but with a toggle option to show it. Not sure how much more time that adds, though. But I agree it's critical to emphasize treating a secret key like a password, and one of the Lab's main purposes is education.
