### ISSUE TITLE
Page - Sign Transaction

### ISSUE THREAD

**Issue by quietbits** [stellar/laboratory#753]
```[tasklist]
- [x] https://github.com/stellar/laboratory/issues/814
- [x] https://github.com/stellar/laboratory/issues/815
- [ ] https://github.com/stellar/laboratory/issues/816
```
Resources: 
- [Figma Design](https://www.figma.com/file/yuikaFOPmJifyAfS90ER6T/Laboratory?type=design&node-id=518-42799&mode=design&t=Ozve3C1WGbvK13yH-0)

**Comment by janewang** [comment]
All tasks in this ticket are merged. Closing
