### ISSUE TITLE
List of Suggestions

### ISSUE THREAD

**Issue by jeesunikim** [stellar/laboratory#793]
This is a list of things that we might consider to implement at the end of the v2 development.

- [x] [Development] should we save the entire `network` information in the url parameters? We might need to display all of the information for `custom` network. However, `TESTNET`, `MAINNET`, and `FUTURENET` do not allow configuration to these fields so we might not need to display all of that (our old lab displays only the network id). 
- [x] [[Design for Endpoints](https://www.figma.com/file/yuikaFOPmJifyAfS90ER6T/Laboratory?type=design&node-id=1775-30706&mode=design&t=Bsjhwi7jPvCTaNqt-0)] It would be nice to have a clear instruction about filters. At least one of the fields is required, but we mention in the labels that they're optional. Let's come back to this after implementing required forms.
- [ ] [Design for Muxed Account] It would be nice to include [this doc](https://developers.stellar.org/docs/learn/encyclopedia/pooled-accounts-muxed-accounts-memos) which is much friendlier bersion than `CAP27` and `SEP23`
- [x] Path Endpoint: this is how the current lab works as well. But ideally, `destination_asset` shouldn't display an error by default
- [ ] `validate.amount`: it accepts leading zero but horizon corrects it. frontend should follow what horizon does.
- [x] Ledger's error `Missing critical parameter` to be more specific ([slack msg](https://stellarfoundation.slack.com/archives/DP2RP5P0E/p1718115643318239?thread_ts=1718115498.393279&cid=DP2RP5P0E))
- [x] analytics

**Comment by janewang** [comment]
Close in favor of https://github.com/stellar/laboratory/issues/1086 and https://github.com/stellar/laboratory/issues/1087
