### ISSUE TITLE
[Fund Account] Page behavior for different network

### ISSUE THREAD

**Issue by janewang** [stellar/laboratory#820]
This ticket describes the behavior of Fund Account page for different networks

<img width="721" alt="Screenshot 2024-04-09 at 10 29 53 AM" src="https://github.com/stellar/laboratory/assets/734336/3c95ea66-80d4-455f-a07a-07de88a666f6">

- Mainnet: [Show empty state](https://www.figma.com/file/yuikaFOPmJifyAfS90ER6T/Laboratory?type=design&node-id=2466%3A11113&mode=design&t=TXUXm2PTxu0wO61j-1) 
- Testnet/Futurenet: The fund account page is show as designed. The account field is not prefilled
- Custom: If the friendbot URL is available if from the RPC and is returning 200, show this page and fund using the URL. Otherwise, show empty state.

**Comment by jeesunikim** [comment]
> Custom: If the friendbot URL is available if from the RPC and is returning 200, show this page and fund using the URL. Otherwise, show empty state.

What do you think of showing the fund page and returning an error if the url isn't legitimate
