### ISSUE TITLE
Network statistics page

### ISSUE THREAD

**Issue by irisli** [stellar/laboratory#87]
It would be great to have a page that will fetch network statistics for the current network.

Then, this could be a good source of statistics and it would work anywhere there is a horizon instance. Here is a unordered list of such possible statistics:
- Number of lumens
- Current ledger height
- Last ledger closed time (likely a few seconds ago, and it will flash demonstrating that new ledgers are created every few seconds)
- Horizon stats

**Comment by jedmccaleb** [comment]
Yeah I agree but I don't think it should go in the lab.
I made this janky thing a while ago. http://stellar.github.io/horizon-status/

**Comment by bartekn** [comment]
I was thinking about this today and I think it would fit in Laboratory. This could be the home page. Laboratory's Endpoint Explorer is kind of block explorer now so I think it would be great to have a stats page there (ex. you could jump quickly to the ledger details from the last ledgers box).

**Comment by jedmccaleb** [comment]
replaced by dashboard
