### ISSUE TITLE
[Endpoints] RPC methods

### ISSUE THREAD

**Issue by quietbits** [stellar/laboratory#874]
![Image](https://github.com/stellar/laboratory/assets/3912060/ff1a2fe0-e907-4b8d-8b95-d002690222c5)

Resources:
- [Figma](https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=1442-22650&t=Rk59xoy2mPeCwtLD-0)
- [Stellar Developer Docs on RPC endpoint](https://developers.stellar.org/docs/data/rpc/api-reference/methods/getEvents)

**Comment by janewang** [comment]
Closing all released with some minor issues
