### ISSUE TITLE
[Endpoints] Navigate JSON response links to appropriate pages on click

### ISSUE THREAD

**Issue by quietbits** [stellar/laboratory#891]
Instead of opening links in a new tab, open links with prefilled params like in Lab v1.

[Lab v1 example](https://github.com/stellar/laboratory/assets/7346473/17031dd2-2c2d-40e2-a885-1e73943d13ee)

**Comment by janewang** [comment]
Solved by PR https://github.com/stellar/laboratory/pull/956
