### ISSUE TITLE
Responsive mobile design implementation

### ISSUE THREAD

**Issue by Row-Bear** [stellar/laboratory#906]
### What version are you using?
Live version at 2024-07-09 20:35UTC

### What did you do?
Visit Laboratory using mobile browsers (Firefox and Opera) 

### What did you expect to see?
All parts of the webpage visible, either through panning or scaled/formatted to fit

### What did you see instead?
Parts of the site that are off screen can not be seen/accessed. 
![Screenshot_20240709-223750](https://github.com/stellar/laboratory/assets/60758353/9a113782-2ef7-48d7-9c6f-7a513327073d)
The view won't pan further right than shown in the screenshot. 
The horizontal menu on top does not pan at all. 
Setting the browser to desktop view resolves this. 

Edit: I just saw that it wasn't supposed to be published yet, sorry if I was premature in raising this!

**Comment by quietbits** [comment]
Thanks for submitting this issue, @Row-Bear ! We'll fix this before the official launch. :wink:

**Comment by janewang** [comment]
@Row-Bear  Please visit the new Stellar Lab (https://beta-laboratory.stellar.org/) and report any bugs at our GitHub Issues page (https://github.com/stellar/laboratory/issues). Happy testing! 💖 Thank you for your support! 🫶

**Comment by jeesunikim** [comment]
similar report from [tyler](https://discord.com/channels/897514728459468821/1260352318877204630/1260383113805303928) to make it usable on mobile

> Again we don’t need a special design. Just don’t force the window to not allow overscroll and place a min width and height

**Comment by janewang** [comment]
Mobile design from @charles-sdf is linked here: https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=3876-19860&m=dev
