### ISSUE TITLE
Web server error when reloading the lab if there was an XDR imported

### ISSUE THREAD

**Issue by earrietadev** [stellar/laboratory#908]
### What version are you using?

Beta lab (https://beta-laboratory.stellar.org/)

### What did you do?

Load the website, go to `Transactions`, go to `sign transaction`, import a valid XDR, try to reload the website and you will get an error message.

### What did you expect to see?

The website

### What did you see instead?

![Screenshot 2024-07-10 at 00 08 48](https://github.com/stellar/laboratory/assets/18198917/8591db56-b56e-4a7d-b3ef-f593dbf2570b)

**Comment by janewang** [comment]
I think this maybe an ops issue. I will send to them. Thanks for reporting @earrietadev

**Comment by janewang** [comment]
Closing as this is an dev ops issue. Please reopen if this issue persists
