### ISSUE TITLE
Ledger signing not working on Firefox on Beta

### ISSUE THREAD

**Issue by jeesunikim** [stellar/laboratory#909]

**Comment by quietbits** [comment]
@jeesunikim , when you work on this, could you please update `@ledgerhq` dependencies? 🙏

**Comment by jeesunikim** [comment]
closing this. [Firefox 114 broke U2F compatibility (ledger)](https://support.ledger.com/article/10525823141917-zd?redirect=false#:~:text=Firefox%20users%3A%20Firefox%20114%20broke,of%20MetaMask%20and%20Chrome%20installed.) 

> Firefox users: [Firefox 114 broke U2F compatibility](https://github.com/MetaMask/metamask-extension/issues/18566) -  disrupting the ability to connect Ledger or any other hardware wallets to MetaMask. Please use other browsers which support U2F or WebHID connection method type (eg. Chrome, Brave).
