### ISSUE TITLE
Change layout of Endpoint Explorer

### ISSUE THREAD

**Issue by bartekn** [stellar/laboratory#91]
The current layout of Endpoint Explorer is wasting a lot of space and requires users to scroll every time they want to change the endpoint:
![laboratory](https://cloud.githubusercontent.com/assets/464938/13372953/0dbe3fa8-dd5a-11e5-8f4e-364e6104975a.png)

I propose to merge "resource" and "endpoint" menus into one, expandable menu (like the one in the devportal). Endpoint options and response can be moved to the right side of the menu:
![stellar laboratory](https://cloud.githubusercontent.com/assets/464938/13372964/86b4dff2-dd5a-11e5-8a66-516bfe664f74.png)

**Comment by jedmccaleb** [comment]
hmm idk. I'd rather use that space a place to put a description of the chosen endpoint

**Comment by irisli** [comment]
In my original mockups of the laboratory, there was some docs stuff on the right side of the page.

I think moving it there would not be helpful because it would cram everything into a small space.

**Comment by jessica-collier** [comment]
Agree with @jedmccaleb and @irisli, though I do think it's a problem that, once the user selects an endpoint, a new interactive form appears at the base of the screen. We might want to move them down automatically or otherwise highlight this section more aggressively when it appears.
