### ISSUE TITLE
Update Nav to utilize vertical space better

### ISSUE THREAD

**Issue by charles-sdf** [stellar/laboratory#915]
Currently the Nav takes up too much space. Updated [designs](https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=3902-17577&t=BKQT721qcN2QXheV-1) here for a small nav.

- Move the top level links up to be next to the Logo
- Truncate _Laboratory_ to _Lab_
- Updated current states on side nav and icon placement so that top level categories like RPC/Horizon Endpoints are collapsable

**Comment by jeesunikim** [comment]
can you confirm that we no longer want "View Documentation" in the nav?

![Image](https://github.com/user-attachments/assets/961ef413-f882-4df2-8c50-d3d8601d152a)

**Comment by charles-sdf** [comment]
hey! updated the designs with the link + icon

https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=3902-17577&t=t5CrbPfz3j8ps9LK-1

**Comment by jeesunikim** [comment]
Updated! @charles-sdf should be up on beta site soon (please check it on monday!)

**Comment by jeesunikim** [comment]
I closed this issue cc @charles-sdf
