### ISSUE TITLE
getLedgerEntries should be update to the new design

### ISSUE THREAD

**Issue by sdfcharles** [stellar/laboratory#916]
Currently, we only have the ability to paste a string. We need to add the ability to paste an XDR string or use ledger entry keys.
Updated [designs](https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=3954-16637&t=jy1yQh2I0VrK3EDO-0) here.

Jane:

> Once you put in the XDR, it just parses into the form below and populate the form and you can edit the form and add more fields or the DR directly

**Comment by janewang** [comment]
I think we need to reiterate on the design somewhat

**Comment by dev0614** [comment]
I think this figma design use Shadcn UI framework...
Currently, project progress?

**Comment by janewang** [comment]
@jeesunikim I think @charles-sdf and I have finalized the `getLedgerEntries` design

**Comment by dev0614** [comment]
Yeah, I checked the figma design. and now I mean, will develop the Frontend based on UI/UX

**Comment by janewang** [comment]
@dev0614 We may need the assignee to work on this. We will consider opening bounties in the future so that you could contribute to our many codebases. Thank you for your interest :)

**Comment by dev0614** [comment]
Do I need to make new repo?
or will you make new repo?

**Comment by janewang** [comment]
We are making this changes, thank you

**Comment by dev0614** [comment]
If that is ready for development, let me know that.
Thank you for your update.

**Comment by jeesunikim** [comment]
`getLedgerEntries` only takes in `keys` not `xdr`. Its response returns `xdr`. Why are we accepting `xdr`? @janewang

**Comment by janewang** [comment]
@jeesunikim and @charles-sdf let's connect on this today so we are aligned
