### ISSUE TITLE
Add meta tags and og:image (webpack)

### ISSUE THREAD

**Issue by irisli** [stellar/laboratory#92]
This can be done by either using this webpack plugin: https://www.npmjs.com/package/html-webpack-plugin or more simply by doing `require('index.html')` somehow.

The meta tags and og:image would be good for previews in social media tools such as Slack

**Comment by bartekn** [comment]
Turned out we're already using `html-webpack-plugin` to generate `index.html` file automatically. Done in `ogtags` branch. Simply add tags you need.

**Comment by irisli** [comment]
We also need to decide on what will go in the screenshot

**Comment by litnerdy** [comment]
Awesome, this will be great for sharing the links. It would be great to have an automatically generated image of the webpage itself, but I'm not sure that's possible, or how much dev time that would be. If there's a pre-existing tool, we should definitely use it. If not, we could do a stock image as default. Ex:

![screen shot 2016-03-01 at 4 32 55 pm](https://cloud.githubusercontent.com/assets/8799534/13446791/4d9758ee-dfcb-11e5-9199-170ffade8bea.png)

**Comment by irisli** [comment]
Yeah, it wouldn't be possible to have an automatically generated image (and I'm not sure we want that either since we want to fine tune it).

Also, this issue is for the laboratory, so using the developers site would be a bit weird. I was thinking of using something from the laboratory.

**Comment by litnerdy** [comment]
Ah, got it. In that case, something like this might be good:

![screen shot 2016-03-01 at 4 48 55 pm](https://cloud.githubusercontent.com/assets/8799534/13447076/8c9f0b2a-dfcd-11e5-8606-d739c376926d.png)

I like the idea of having it show the builder, since that's one of the coolest things you can do it the lab, imo. We could also show a filled-in transaction there, if we want.

**Comment by irisli** [comment]
Okay, I'll make an `og:image` with a screenshot of something like this
