### ISSUE TITLE
sendTransaction and simulateTransaction RPC endpoints are accept incorrect type

### ISSUE THREAD

**Issue by janewang** [stellar/laboratory#925]
For RPC endpoints, the sendTransaction and simulateTransaction page should accept `transaction`. They are currently accept Transaction Hash. In order to send or simulate transactions, it should be the transaction envelope that's provided. The [API documentation](https://developers.stellar.org/docs/data/rpc/api-reference/methods/sendTransaction) for these endpoints are here. 

- [sendTransaction](https://beta-laboratory.stellar.org/endpoints/rpc/send-transaction?$=network$id=mainnet&label=Mainnet&horizonUrl=https:////horizon.stellar.org&rpcUrl=https:////testnet.stellar.validationcloud.io//v1//cP0_YacCIsGeCG0YjCy2TWVN7Z_TbiYBHnTONTCJWCE&passphrase=Public%20Global%20Stellar%20Network%20/;%20September%202015;;)
- [simulateTransaction](https://beta-laboratory.stellar.org/endpoints/rpc/send-transaction?$=network$id=mainnet&label=Mainnet&horizonUrl=https:////horizon.stellar.org&rpcUrl=https:////testnet.stellar.validationcloud.io//v1//cP0_YacCIsGeCG0YjCy2TWVN7Z_TbiYBHnTONTCJWCE&passphrase=Public%20Global%20Stellar%20Network%20/;%20September%202015;;)

I also suggest that the input box becomes a textarea box as transaction envelopes are quite large, more than one line.

**Comment by jeesunikim** [comment]
Fixed [here ](https://github.com/stellar/laboratory/pull/911)

**Comment by janewang** [comment]
Closing this bug
