### ISSUE TITLE
RPC endpoint getTransactions should accept startLedger and pagination, not hash

### ISSUE THREAD

**Issue by janewang** [stellar/laboratory#927]
### What version are you using?

RPC `getTransactions` on Lab v2 is [shown here](https://beta-laboratory.stellar.org/endpoints/rpc/get-transactions?$=network$id=testnet&label=Testnet&horizonUrl=https:////horizon-testnet.stellar.org&rpcUrl=https:////soroban-testnet.stellar.org&passphrase=Test%20SDF%20Network%20/;%20September%202015;;).

getTransactions is a way to pull back multiple transactions, so it needs startLedger number and pagination. It currently accepts a transaction hash which make sense for pulling back a single transaction, not multiple transactions. 

The API documentation for `getTransactions` (plural) is [here](https://developers.stellar.org/docs/data/rpc/api-reference/methods/getTransactions). It should not be confused with `getTransaction` (singular).

**Comment by jeesunikim** [comment]
Please see the latest [here](https://github.com/stellar/laboratory/pull/911)

**Comment by janewang** [comment]
Closed
