### ISSUE TITLE
Code folding in XDR view

### ISSUE THREAD

**Issue by orbitlens** [stellar/laboratory#938]
Could you please add collapsible branches to allow code blocks folding/unfolding in the "View XDR" interface (JSON view)?

Also, it would be nice to allow full-screen view for the parsed XDR output. For transaction meta and other XDR types with large output size, the viewport is too small.

**Comment by janewang** [comment]
@orbitlens Thanks for the feedback. Could I close this ticket in favor of this https://github.com/stellar/laboratory/issues/912

It has code folding

**Comment by orbitlens** [comment]
@janewang Oh, I missed this ticket. Thanks for the heads up!
