### ISSUE TITLE
XDR decoding bug in laboratory beta

### ISSUE THREAD

**Issue by dmkozh** [stellar/laboratory#947]
### What version are you using?

beta-laboratory.stellar.org

### What did you do?

Tried to decode `AA+L+AAAAAYAAAAAAAAAAb1aLhk3xbHbCuEm4ag6kEuAl+FYXGYlTaZG6gNF1NDpAAAAFQshA28ulzCuAAAAAAAAAAEAAAAA` blob as `LedgerEntry` XDR

### What did you expect to see?
```
key: [scvLedgerKeyNonce]
nonceKey: **801925984706572462**
```

as per the current version of laboratory

### What did you see instead?
```
"ledger_key_nonce":
{
"nonce":
**801925984706572400**,
},
```

This seems really concerning given that only 1 byte differs in decoded values.

**Comment by janewang** [comment]
Thank you for raising this @dmkozh

**Comment by quietbits** [comment]
@dmkozh Could you please confirm that [this PR](https://github.com/stellar/laboratory/pull/953) fixes the issue?

**Comment by dmkozh** [comment]
> @dmkozh Could you please confirm that [this PR](https://github.com/stellar/laboratory/pull/953) fixes the issue?

Yes, looks correct, thanks for the quick fix.
