### ISSUE TITLE
Cannot follow links from within lab v2 (parity issue with V1)

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/laboratory#950]
In the previous version of lab, clicking on any of the links from a result from horizon would navigate to the corresponding laboratory page with fields prefilled.

For example:
Go to “Horizon Endpoints” -> ledgers -> all ledgers -> select “Desc” (to get the latest ledgers)
in the JSON response scroll down and click on an “href” like the one under “transactions"

result:
Browser navigates to something like https://horizon-testnet.stellar.org/ledgers/1032951/transactions%7B?cursor,limit,order}  (which is a bad URL by the way )

expected result:
should be taken to the “horizon endpoints” -> transactions-> transactions for Ledger -> “Ledger sequence” should be prefilled with the right number

**Comment by quietbits** [comment]
Is this related to [this issue](https://github.com/stellar/laboratory/issues/891)?
