### ISSUE TITLE
XDR not being decoded in lab V2  (parity issue with V1)

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/laboratory#951]
In the previous version of lab clicking on a base 64 encoded XDR value, would take the user to the decoded XDR page.

For example:
Go to “Horizon Endpoints” -> ledgers -> all ledgers -> select “Desc” (to get the latest ledgers)

Result:
In the JSON response, clicking on “header_xdr” does not do anything.

Expected result:
clicking on “header_xdr” (or the base 64 value), should navigate to XDR -> XDR to JSON -> the base 64 field and XDR type should be prefilled.

**Comment by quietbits** [comment]
@MonsieurNicolas Could you please provide a screenshot of which `header_xdr` you mean? They are not clickable for me in Chrome or Firefox on Ubuntu in Lab v1.

https://github.com/user-attachments/assets/5621e920-7b3e-412c-bc6c-91a123ab0698

**Comment by janewang** [comment]
@MonsieurNicolas @quietbits I think this is a good to add for Horizon and RPC for sure. 

For RPC, George has enabled response in JSON with this PR. We will align Lab once this feature goes live.  https://github.com/stellar/soroban-rpc/commit/b88b421672849cf431898bd331f69eb2fc4e5772

**Comment by MonsieurNicolas** [comment]
Looks like this was only partially fixed.
I see that RPC related endpoints still only shows text as raw base64 (not linking to the decoder), like:
* [get transactions](https://lab.stellar.org/endpoints/rpc/get-transactions?$=network$id=testnet&label=Testnet&horizonUrl=https:////horizon-testnet.stellar.org&rpcUrl=https:////soroban-testnet.stellar.org&passphrase=Test%20SDF%20Network%20/;%20September%202015;&endpoints$params$startLedger=1262569;;)
* [get transaction](https://lab.stellar.org/endpoints/rpc/get-transaction?$=network$id=testnet&label=Testnet&horizonUrl=https:////horizon-testnet.stellar.org&rpcUrl=https:////soroban-testnet.stellar.org&passphrase=Test%20SDF%20Network%20/;%20September%202015;&endpoints$params$transaction=0bf8d5ebb7c0684032eb22035c15919a4fa4f23a2db85f0e9e6311c28cb311e2;;)
