### ISSUE TITLE
Wrong label in the XDR pages, says “Transaction XDR” (lab v2)

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/laboratory#952]
The text input field is labeled as “Transaction” in both “XDR to JSON”  and “JSON to XDR”.

This is inaccurate as the type could be anything (not just `TransactionEnvelope` type).

**Comment by janewang** [comment]
Should say `Base-64 encoded XDR`

Thanks @MonsieurNicolas for raising these issues
