### ISSUE TITLE
Missing debug tooling (signature check in XDR JSON)

### ISSUE THREAD

**Issue by jopmiddelkamp** [stellar/laboratory#968]
I appreciate the recent update to the laboratory tools, especially the new design that makes it easier on the eyes during nighttime work.

### What problem does your feature solve?
I’ve noticed that some essential debugging tools seem to be missing. Specifically, I’m currently working with a TransactionEnvelope XDR that returns a bad_auth result, likely due to an invalid signature. Previously, the debug information included an indicator identifying which key caused the bad authentication, which was incredibly helpful for pinpointing issues.

### What would you like to see?
I would like the previous behavior restored, where the tool clearly identifies the key responsible for the bad_auth result.

### What alternatives are there?
Is there a way to access the legacy laboratory tools in the meantime?

**Comment by quietbits** [comment]
@jopmiddelkamp, thanks for the feedback! Could you please provide the XDR that we can use as an example? It will help us understand what exactly is missing. :pray: 

You can view the previous Lab at https://old-lab.stellar.org/.

**Comment by jopmiddelkamp** [comment]
[new lab](https://lab.stellar.org/xdr/view?$=network$id=mainnet&label=Mainnet&horizonUrl=https:////horizon.stellar.org&rpcUrl=&passphrase=Public%20Global%20Stellar%20Network%20/;%20September%202015;&xdr$blob=AAAAAgAAAADovY4jbWG6etPHespJeEhq7s5BULrSI2kAU9ci2wdTwQAAAZACqmHIAAABdQAAAAAAAAAAAAAABAAAAAEAAAAAfdWMBk4ff6lifyvekokjwKgYgFWnqPhui94pghHiAx8AAAAQAAAAAOi9jiNtYbp608d6ykl4SGruzkFQutIjaQBT1yLbB1PBAAAAAQAAAADovY4jbWG6etPHespJeEhq7s5BULrSI2kAU9ci2wdTwQAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAXl+Smng//JynQzifcaf98urzBae78Fz+S9koMDDwWxlgAAAAAAAAAAQAAAADovY4jbWG6etPHespJeEhq7s5BULrSI2kAU9ci2wdTwQAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAIVKmAMhoBAskGV1YdBBm5A8imsavUc6e+Ievv4goTm8AAAACAAAAAQAAAADovY4jbWG6etPHespJeEhq7s5BULrSI2kAU9ci2wdTwQAAABEAAAAAAAAAArL9Q7cAAABArLpmhp180FS3BkgUjB6oGvsy6HIorf3P6a6//vXKfg8kEWXQAkAVU416Yh+SFkf2mM88KQmg9IwD6KwvZBEcRAFbyt//IAAABAj8ApNTcN2sZ9hfr4icRWebpn8OS+ORFSErbIb86LRmD+heuZ3f0jy1zsG0NuOl2O6wXiHkzY96Vs1BnG43e8Aw==;;):
<img width="1066" alt="image" src="https://github.com/user-attachments/assets/565d9107-fa7a-483d-b392-6bc400038eb2">

[old lab](https://old-lab.stellar.org/#xdr-viewer?input=AAAAAgAAAADovY4jbWG6etPHespJeEhq7s5BULrSI2kAU9ci2wdTwQAAAZACqmHIAAABdQAAAAAAAAAAAAAABAAAAAEAAAAAfdWMBk4ff6lifyvekokjwKgYgFWnqPhui94pghHiAx8AAAAQAAAAAOi9jiNtYbp608d6ykl4SGruzkFQutIjaQBT1yLbB1PBAAAAAQAAAADovY4jbWG6etPHespJeEhq7s5BULrSI2kAU9ci2wdTwQAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAXl%2BSmng%2FJynQzifcaf98urzBae78Fz%2BS9koMDDwWxlgAAAAAAAAAAQAAAADovY4jbWG6etPHespJeEhq7s5BULrSI2kAU9ci2wdTwQAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAIVKmAMhoBAskGV1YdBBm5A8imsavUc6e%2BIevv4goTm8AAAACAAAAAQAAAADovY4jbWG6etPHespJeEhq7s5BULrSI2kAU9ci2wdTwQAAABEAAAAAAAAAArL9Q7cAAABArLpmhp180FS3BkgUjB6oGvsy6HIorf3P6a6%2FvXKfg8kEWXQAkAVU416Yh%2BSFkf2mM88KQmg9IwD6KwvZBEcRAFbyt%2FIAAABAj8ApNTcN2sZ9hfr4icRWebpn8OS%2BORFSErbIb86LRmD%2BheuZ3f0jy1zsG0NuOl2O6wXiHkzY96Vs1BnG43e8Aw%3D%3D&type=TransactionEnvelope&network=public):
<img width="1139" alt="image" src="https://github.com/user-attachments/assets/d05e1c87-d776-4dae-953e-4dd3f8c6743b">

**Comment by janewang** [comment]
![image (1)](https://github.com/user-attachments/assets/6bf4bba9-9a7f-4a34-afc9-913526637b1d)

**Comment by janewang** [comment]
@sdfcharles We could add text like "Signatures checked" and @quietbits mentioned needing loading state while the signatures are being checked

**Comment by sdfcharles** [comment]
[Signatures debug designs](https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=4994-21021&t=HfMKETEZJlfsLxYL-1)

[Loading screen](https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=4994-21237&t=HfMKETEZJlfsLxYL-1)

**Comment by janewang** [comment]
Please see this issue for potential issue with the signature error checking https://github.com/stellar/laboratory/issues/517
