### ISSUE TITLE
Unable to submit transaction on Mainnet

### ISSUE THREAD

**Issue by Labetto** [stellar/laboratory#969]
### What did you do?
I have built a transaction on Stellar Laboratory Mainnet new version under Windows11 / Brave. Once signed, there's no way to submit the transaction, the submit button is grayed out.

### What did you expect to see?
Be able to submit the transaction to the network.

### What did you see instead?

No actions possible at the submitting stage.

**Comment by janewang** [comment]
@Labetto I think you need to add a RPC url for mainnet. You can find publicly available ones from our dev docs: https://developers.stellar.org/docs/data/rpc/rpc-providers#publicly-accessible-rpc-urls

**Comment by janewang** [comment]
We will add some messaging indicating the need for providing mainnet third party URLs.

**Comment by Labetto** [comment]
I have tried with both public RPC's and I am able to submit the transaction now. But it won't get through even when increasing the fees a lot and I get a blank screen with "Application error: a client-side exception has occurred" each time having to rebuild the transaction from scratch. Network is busy right now so I will try later to see if it goes trough then.

**Comment by janewang** [comment]
@Labetto We saw other reports of _"Application error: a client-side exception has occurred". Ops is going to take a look_

**Comment by shiny-mountain** [comment]
When I try to submit transaction on Mainnet, I get an error 
`Refused to connect to 'https://soroban-rpc.****my-domain****/' because it violates the following Content Security Policy directive: "connect-src 'self' https://9sl3dhr1twv1.statuspage.io/api/v2/ https://stellar-mainnet.liquify.com/ https://stellar.liquify.com/ https://soroban-rpc.mainnet.stellar.gateway.fm/ https://soroban-rpc.testnet.stellar.gateway.fm/ *.stellar.org".`

**Comment by shiny-mountain** [comment]
Why can't I submit a transaction without entering an rpc-server? In the old lab everything is submits perfectly well without rpc-servers, including soroban transactions. Make the "Submit transaction" button active and "Simulate transaction" inactive if no rpc-server is entered.

**Comment by Kelblueshoes** [comment]
has anyone found a solution to this yet? I have no clue how to use what they suggest.

**Comment by Kelblueshoes** [comment]
So, do we just hangout until they fix this bug?? God forbid there is a power outage or something.

**Comment by janewang** [comment]
Please try to use validation cloud: https://developers.stellar.org/docs/data/rpc/rpc-providers#ecosystem-providers
And add the URL to the network tab.

Alternatively you can use Horizon to submit a TX here https://lab.stellar.org/endpoints/transactions/post?$=network$id=testnet&label=Testnet&horizonUrl=https:////horizon-testnet.stellar.org&rpcUrl=https:////soroban-testnet.stellar.org&passphrase=Test%20SDF%20Network%20/;%20September%202015;;

We're adding a fix for this in the coming weeks.

**Comment by Kelblueshoes** [comment]
I guess I will wait for the fix in the coming weeks. I cant seem to get any of the solutions to work without creating a custom network. Which isnt what I really want to do. I want to post on the main net. Thank you for your attention to the matter. I appreciate it. I Cant wait for this to be fixed.

**Comment by shiny-mountain** [comment]
> I guess I will wait for the fix in the coming weeks. I cant seem to get any of the solutions to work without creating a custom network. Which isnt what I really want to do. I want to post on the main net. Thank you for your attention to the matter. I appreciate it. I Cant wait for this to be fixed.
Having your own rpc-server doesn't help in any way:) I have one, but it still doesn't work. I'll also be waiting for the fix.

**Comment by janewang** [comment]
@Labetto  This is now fixed. Thank you for your patience 🙏

https://lab.stellar.org/transaction/submit?$=network$id=mainnet&label=Mainnet&horizonUrl=https:////horizon.stellar.org&rpcUrl=&passphrase=Public%20Global%20Stellar%20Network%20/;%20September%202015;;
