### ISSUE TITLE
RPC endpoints should not enable submit if mainnet RPC is not available

### ISSUE THREAD

**Issue by janewang** [stellar/laboratory#975]
### What did you do?
Step 1. Switched to mainnet 
Step 2. Go to [getHealth on the RPC](https://lab.stellar.org/endpoints/rpc/get-health?$=network$id=mainnet&label=Mainnet&horizonUrl=https:////horizon.stellar.org&rpcUrl=&passphrase=Public%20Global%20Stellar%20Network%20/;%20September%202015;;)
Step 3. See that you can submit without an RPC endpoint. 

### What did you expect to see?
The submit button should be disabled and we should show a warning: https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=4923-21029&m=dev

### What did you see instead?

<img width="1016" alt="Screenshot 2024-08-22 at 12 38 41 PM" src="https://github.com/user-attachments/assets/8165e8ce-181a-4d39-a259-816d07b2d33e">

**Comment by janewang** [comment]
@sdfcharles will attach the design

**Comment by sdfcharles** [comment]
[Designs](https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=4923-21029&t=L9seWJ6VjHrZckr4-1)
