### ISSUE TITLE
Pretty print JSON on RPC payloads

### ISSUE THREAD

**Issue by accordeiro** [stellar/laboratory#978]
We already pretty print JSON on the JSON<>XDR functionality.

<img width="991" alt="Screenshot 2024-08-22 at 1 36 55 PM" src="https://github.com/user-attachments/assets/8f0580bf-b06d-4245-bb7c-1bcbd9c0ee0f">

I'd like to have the same monospaced, collapsible, syntax-highlighted JSON on RPC payloads, such as on this screen:

<img width="979" alt="Screenshot 2024-08-22 at 1 37 48 PM" src="https://github.com/user-attachments/assets/8963b983-d6e4-400a-b3f3-103ff36d5fa4">

This will enable easier parsing / browsing of the API call that will be submitted.

**Comment by Shaptic** [comment]
@accordeiro if you want, you guys can wait until we release the next minor version of RPC which will let you get the responses as JSON by default via an `xdrFormat: "json"` parameter! :+1:

**Comment by janewang** [comment]
@Shaptic I can't wait for the next version of the RPC with JSON! 🎉 

This is the payload that's submitted to the RPC endpoint that we want to prettify. We should consistently prettify JSON in Lab

**Comment by janewang** [comment]
Discussed with @quietbits that we will change to pretty print without the toggle
