### ISSUE TITLE
Info tooltip on RPC endpoints references Horizon

### ISSUE THREAD

**Issue by accordeiro** [stellar/laboratory#979]
[Version commit hash: bd35969]

The tooltip under the RPC endpoints sections references Horizon (see screenshot below), even though these endpoints are exclusively related to RPC. We should change the tooltip text to correctly reflect that.

<img width="991" alt="Screenshot 2024-08-22 at 1 39 05 PM" src="https://github.com/user-attachments/assets/e2d055e0-607f-477a-b024-2197959e30a7">

**Comment by janewang** [comment]
To respond to @quietbits question on slack, the text should say 

This tool can be used to run queries against the [REST API endpoints](https://developers.stellar.org/docs/data/rpc) of RPC servers. RPC is one of the developer-facing services for the Stellar ecosystem.
