### ISSUE TITLE
Combine `Params` and `Operations` tabs

### ISSUE THREAD

**Issue by accordeiro** [stellar/laboratory#980]
When I start building a transactions and click "Add Operation", I'm abruptly taken to a different screen without clear indication on how to go back. After trying to understand what happened, I realize there are two tabs: `Params` and `Operations` that alternate depending on the action.

While I feel like I can get used to this flow, it is a bit disruptive, and there's no clear sense of continuity as I'm building out a transaction.

I feel like there are a few small tweaks we can make to deliver a more continuous experience:

1. Add a "Back to operation params" navigation link at the top of the Operations editor.
2. On the Params tab, add an operation counter inside the "Add Operation" button. So after adding 3 operations on the corresponding tab, if I come back to Params, I'd see a button labeled "Add More Operations (3)" that takes me back to the Operation tab.

There's also the possibility of consolidating the two tabs into a single page, and making operations collapsible. This would be my personal preference, but I understand this is less of an incremental change.

Would love your thoughts on this @sdfcharles @janewang

**Comment by tomerweller** [comment]
Agreed that this is confusing. 

> There's also the possibility of consolidating the two tabs into a single page,

I might be biased by old lab, but this seems to me like a good solution

**Comment by janewang** [comment]
@sdfcharles will add the new design and will move to ready for development

**Comment by sdfcharles** [comment]
Updated designs [here](https://www.figma.com/design/yuikaFOPmJifyAfS90ER6T/Laboratory?node-id=5016-23150&t=Sffi6Emq7Mr339KH-1)

cc @quietbits
