### ISSUE TITLE
unable to remove trustline/submit transaction on mainnet

### ISSUE THREAD

**Issue by Kelblueshoes** [stellar/laboratory#988]
### What version are you using? lab.stellar.org

I am to remove trustline/submit transaction. I have no idea how to use what they suggested in a previous post. It doesnt appear that I can even input it. 

### What did you see instead?

```[tasklist]
### Tasks
```

**Comment by janewang** [comment]
@Kelblueshoes This is now fixed. Thank you for your patience 🙏 

https://lab.stellar.org/transaction/submit?$=network$id=mainnet&label=Mainnet&horizonUrl=https:////horizon.stellar.org&rpcUrl=&passphrase=Public%20Global%20Stellar%20Network%20/;%20September%202015;;
