### ISSUE TITLE
errors "create claimable balance/adds 7 zeros to amount

### ISSUE THREAD

**Issue by tdixon1000** [stellar/laboratory#995]

**Comment by tdixon1000** [comment]
I can not complete operation after submitting, errors ,errors...As said, the RPC URL is a new wild card....

**Comment by janewang** [comment]
@tdixon1000 Are you using this page  for [claimable balances](https://lab.stellar.org/endpoints/claimable-balances?$=network$id=testnet&label=Testnet&horizonUrl=https:////horizon-testnet.stellar.org&rpcUrl=https:////soroban-testnet.stellar.org&passphrase=Test%20SDF%20Network%20/;%20September%202015;;) or transaction submission page?

**Comment by tdixon1000** [comment]
This page? this page is where I'm posting of the new V2 is not working like V1 did or anymore....

**Comment by tdixon1000** [comment]
obviously I'm at stellar lab/build transactions V2

**Comment by quietbits** [comment]
@tdixon1000 You want to see the entered amount in the XDR instead of just the raw amount. Do I understand your request correctly?

[Here's a PR](https://github.com/stellar/laboratory/pull/990) that will allow you to submit transactions using Horizon (no RPC URL required). It should be merged this week.

Lab v2
![image](https://github.com/user-attachments/assets/6d3afe0b-a052-4cde-9dc0-32474afd5d9b)

Lab v1
![image](https://github.com/user-attachments/assets/d7d5f999-7ce7-466a-aec0-998c8af3c4dd)

**Comment by tdixon1000** [comment]
So you're saying XDR should show plus 7 zeros?

**Comment by tdixon1000** [comment]
if that is not an issue then great, but I still get error to complete anything as this URL needed for mainnet is a stumper and can only guess that is what is stopping my transaction for a claimable balance

**Comment by tdixon1000** [comment]
still failed,   must be the network issue/URL

Transaction failed
Error result:
{
"message":
"Network Error",
"name":
"AxiosError",
"code":
"ERR_NETWORK",
"config":
{
15 items
"transitional":
{
3 items
"silentJSONParsing":
true,
"forcedJSONParsing":
true,
"clarifyTimeoutError":
false,
},
"adapter":
[
3 items
"xhr",
"http",
"fetch",

**Comment by quietbits** [comment]
Re: the amount. It is correct with all those extra zeroes in XDR. We'll update it to show the actual value like in Lab v1 soon. The amount submitted is correct. Here's an example of a claimable balance I created with the amount `0.0123`.

Claimable balance details
![image](https://github.com/user-attachments/assets/ae2fe319-1179-4b2c-929a-7eb1a6a1c5cc)

Transaction XDR
![image](https://github.com/user-attachments/assets/72624117-2a21-4141-ae5d-40d37ca6d71b)

**Comment by tdixon1000** [comment]
Yes, that would be helpful to be 1 to 1 on the zeros, anyone would look at that and say, huh?    As I did and thought it was a buggy thing causing issues....

I'll figure out the Horizon thing and give it a try...

On another note....I just remembered, I've always had done my work off my iPhone, I noticed I couldn't anymore with V2 as the screen interface was all unmanageable to make anything happen...what is up with that?

**Comment by tdixon1000** [comment]
Ok, the Horizon switch worked, thanks !

**Comment by quietbits** [comment]
> On another note....I just remembered, I've always had done my work off my iPhone, I noticed I couldn't anymore with V2 as the screen interface was all unmanageable to make anything happen...what is up with that?

Yes, we'll make it response so that it can be used on mobile. Here's an issue for that: https://github.com/stellar/laboratory/issues/906.

Thanks for your feedback, @tdixon1000 ! Please let us know if you notice anything else.

**Comment by tdixon1000** [comment]
perfect, thanks again
